CREATE TABLE IRSTE_USER (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    TRAINEE_ID                  TEXT                ,
    DESIGNATION                 TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          PERSON (PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE IRSTE_COMPLAINT(
    ID                          INTEGER             NOT NULL PRIMARY KEY ,
    COMPLAINT_NUMBER            TEXT                NOT NULL,
    LOCATION                    TEXT                NOT NULL,
    UTILITY                     TEXT                NOT NULL,
    GROUP_UTILITY               TEXT                NOT NULL,
    DETAILS                     TEXT                NOT NULL,
    STATUS                      COMPLAINT_STATUS    NOT NULL,
    PERSON                      INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
    RESPONDER                   INTEGER             ,
    ASSISTOR                    INTEGER             ,
    FACILITATOR                 INTEGER             ,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IRSTE_COMPLAINTHISTORY(
  ID                          INTEGER             NOT NULL PRIMARY KEY ,
  COMPLAINT                   INTEGER             NOT NULL REFERENCES IRSTE_COMPLAINT(ID) ON DELETE CASCADE,
  ASSIGNED_TO                 INTEGER             REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
  SUBMITTED_BY                INTEGER             REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
  NEW_STATUS                  COMPLAINT_STATUS    ,
  MODIFIED_DATE               TIMESTAMP
);

CREATE TABLE IRSTE_GROUPLOCATION(
  GROUP_ID                    INTEGER             NOT NULL PRIMARY KEY,
  NAME                        TEXT
);

CREATE TABLE IRSTE_LOCATION(
  ID                          INTEGER             NOT NULL PRIMARY KEY,
  GROUP_ID                    INTEGER             NOT NULL REFERENCES IRSTE_GROUPLOCATION(GROUP_ID) ON DELETE CASCADE,
  NAME                        TEXT
);

CREATE TABLE IRSTE_UTILITYLOCATION(
  LOCATION_ID                 INTEGER             NOT NULL REFERENCES IRSTE_LOCATION(ID) ON DELETE CASCADE,
  UTILITY                     TEXT                NOT NULL,
  UNIQUE (LOCATION_ID, UTILITY)
);

CREATE TABLE IRSTE_USERUTILITIES(
  PERSON_ID                   INTEGER             NOT NULL REFERENCES IRSTE_USER(ID) ON DELETE CASCADE,
  UTILITY                     TEXT                NOT NULL,
  PERSONTYPE                  INTEGER             NOT NULL,
  UNIQUE (PERSON_ID, UTILITY)
);

CREATE TABLE IRSTE_GROUPUTILITY(
  GROUP_NAME                  TEXT             NOT NULL,
  UTILITY                     TEXT,
  UNIQUE (GROUP_NAME, UTILITY)
);


ALTER TABLE CASSINI_OBJECT DROP COLUMN CREATED_BY;
ALTER TABLE CASSINI_OBJECT DROP COLUMN MODIFIED_BY;

ALTER TABLE CASSINI_OBJECT ADD COLUMN CREATED_BY INTEGER REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE;
ALTER TABLE CASSINI_OBJECT ADD COLUMN MODIFIED_BY INTEGER REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE;