package com.cassinisys.plm.model.plm.dto;

import com.cassinisys.platform.model.common.TagDto;
import com.cassinisys.platform.model.core.ObjectType;
import com.cassinisys.platform.model.custom.CustomObject;
import com.cassinisys.plm.model.cm.PLMECO;
import com.cassinisys.plm.model.cm.PLMMCO;
import com.cassinisys.plm.model.cm.dto.DCODto;
import com.cassinisys.plm.model.cm.dto.DCRDto;
import com.cassinisys.plm.model.cm.dto.ECRDto;
import com.cassinisys.plm.model.dto.VarianceDto;
import com.cassinisys.plm.model.mes.*;
import com.cassinisys.plm.model.mes.dto.JigsFixtureDto;
import com.cassinisys.plm.model.mes.dto.MaterialDto;
import com.cassinisys.plm.model.mfr.PLMManufacturer;
import com.cassinisys.plm.model.mfr.PLMManufacturerPart;
import com.cassinisys.plm.model.mfr.PLMSupplier;
import com.cassinisys.plm.model.mro.MROAsset;
import com.cassinisys.plm.model.mro.MROMeter;
import com.cassinisys.plm.model.mro.MROSparePart;
import com.cassinisys.plm.model.mro.WorkRequestDto;
import com.cassinisys.plm.model.mro.dto.MaintenancePlanDto;
import com.cassinisys.plm.model.mro.dto.WorkOrderDto;
import com.cassinisys.plm.model.pdm.PDMAssembly;
import com.cassinisys.plm.model.pdm.PDMDrawing;
import com.cassinisys.plm.model.pdm.PDMPart;
import com.cassinisys.plm.model.pdm.PDMVault;
import com.cassinisys.plm.model.pgc.PGCDeclaration;
import com.cassinisys.plm.model.pgc.PGCSpecification;
import com.cassinisys.plm.model.pgc.PGCSubstance;
import com.cassinisys.plm.model.plm.PLMDocument;
import com.cassinisys.plm.model.plm.PLMItem;
import com.cassinisys.plm.model.plm.PLMNpr;
import com.cassinisys.plm.model.pm.PLMProject;
import com.cassinisys.plm.model.pm.ProgramDto;
import com.cassinisys.plm.model.pqm.PQMPPAP;
import com.cassinisys.plm.model.pqm.PQMSupplierAudit;
import com.cassinisys.plm.model.pqm.dto.*;
import com.cassinisys.plm.model.req.PLMRequirementDocument;
import com.cassinisys.plm.model.req.PLMRequirementVersion;
import com.cassinisys.plm.model.rm.CommonFileDto;
import com.cassinisys.plm.model.wf.PLMWorkflowDefinition;
import lombok.Data;
import org.springframework.data.domain.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by subramanyam on 22-06-2020.
 */
@Data
public class TopSearchDto {

    private Long itemsCount = 0L;
    private Long nprCount = 0L;
    private Long ecoCount = 0L;
    private Long projectsCount = 0L;
    private Long programCount = 0L;
    private Long requirementDocumentsCount = 0L;
    private Long requirementsCount = 0L;
    private Long workflowCount = 0L;
    private Long filesCount = 0L;
    private Long productInspectionPlanCount = 0L;
    private Long materialInspectionPlanCount = 0L;
    private Long itemInspectionCount = 0L;
    private Long materialInspectionCount = 0L;
    private Long problemReportCount = 0L;
    private Long ncrCount = 0L;
    private Long qcrCount = 0L;
    private Long ppapCount = 0L;
    private Long ecrCount = 0L;
    private Long dcoCount = 0L;
    private Long dcrCount = 0L;
    private Long mcoCount = 0L;
    private Long deviationCount = 0L;
    private Long waiverCount = 0L;
    private Long plantCount = 0L;
    private Long assemblyLineCount = 0L;
    private Long workCenterCount = 0L;
    private Long machineCount = 0L;
    private Long equipmentCount = 0L;
    private Long instrumentCount = 0L;
    private Long toolCount = 0L;
    private Long jigCount = 0L;
    private Long fixtureCount = 0L;
    private Long materialCount = 0L;
    private Long manPowerCount = 0L;
    private Long shiftCount = 0L;
    private Long operationCount = 0L;
    private Long mfrCount = 0L;
    private Long mfrPartCount = 0L;
    private Long supplierCount = 0L;
    private Long supplierAuditCount = 0L;
    private Long assetCount = 0L;
    private Long meterCount = 0L;
    private Long sparePartCount = 0L;
    private Long maintenancePlanCount = 0L;
    private Long workRequestCount = 0L;
    private Long workOrderCount = 0L;
    private Long pgcSubstanceCount = 0L;
    private Long pgcSpecificationCount = 0L;
    private Long pgcDeclarationCount = 0L;
    private Long pdmVaultCount = 0L;
    private Long pdmAssemblyCount = 0L;
    private Long pdmPartCount = 0L;
    private Long pdmDrawingCount = 0L;
    private Long customObjectCount = 0L;
    private Long documentCount = 0L;
    private Long tagsCount = 0L;

    private Page<PLMItem> items;
    private Page<PLMNpr> nprs;
    private Page<PLMECO> ecos;
    private Page<PLMProject> projects;
    private Page<ProgramDto> programs;
    private Page<PLMRequirementDocument> requirementDocuments;
    private Page<PLMRequirementVersion> requirements;
    private Page<PLMWorkflowDefinition> workflows;
    private Page<CommonFileDto> files;
    private Page<InspectionPlansDto> inspectionPlans;
    private Page<InspectionsDto> inspections;
    private Page<ProblemReportsDto> problemReports;
    private Page<NCRsDto> ncrs;
    private Page<QCRsDto> qcrs;
    private Page<PQMPPAP> ppaps;
    private Page<ECRDto> ecrs;
    private Page<PLMMCO> mcos;
    private Page<DCODto> dcos;
    private Page<DCRDto> dcrs;
    private Page<VarianceDto> variances;
    private Page<MESPlant> plants;
    private Page<MESAssemblyLine> assemblyLines;
    private Page<MESWorkCenter> workCenters;
    private Page<MESMachine> machines;
    private Page<MESEquipment> equipments;
    private Page<MESInstrument> instruments;
    private Page<MESTool> tools;
    private Page<JigsFixtureDto> jigs;
    private Page<JigsFixtureDto> fixtures;
    private Page<MaterialDto> materials;
    private Page<MESManpower> manpowers;
    private Page<MESShift> shifts;
    private Page<MESOperation> operations;
    private Page<PLMManufacturer> manufacturers;
    private Page<PLMManufacturerPart> manufacturerParts;
    private Page<PLMSupplier> suppliers;
    private Page<PQMSupplierAudit> supplierAudits;
    private Page<MROAsset> assets;
    private Page<MROMeter> meters;
    private Page<MROSparePart> spareParts;
    private Page<MaintenancePlanDto> maintenancePlans;
    private Page<WorkRequestDto> workRequests;
    private Page<WorkOrderDto> workOrders;
    private Page<PGCSubstance> pgcSubstances;
    private Page<PGCSpecification> pgcSpecifications;
    private Page<PGCDeclaration> pgcDeclarations;
    private Page<PDMAssembly> pdmAssemblies;
    private Page<PDMVault> pdmVaults;
    private Page<PDMPart> pdmParts;
    private Page<PDMDrawing> pdmDrawings;
    private Page<CustomObject> customObjects;
    private Page<PLMDocument> documents;
    private Page<TagDto> tags;
    private List<ObjectType> tagObjectTypes = new ArrayList<>();

    private Boolean first = false;
    private Boolean last = false;
}
