package com.cassinisys.plm.model.pdm;

public enum PDMObjectType {
    PDM_ASSEMBLY,
    PDM_PART,
    PDM_DRAWING,
    PDM_DRAWINGTEMPLATE,
    PDM_REVISIONMASTER,
    PDM_CONFIGURATION,
    PDM_BOMOCCURRENCE,
    PDM_FILE,
    PDM_FILEVERSION,
    PDM_FOLDER,
    PDM_VAULT,
    PDM_COMMIT,
    PDM_GITHUBACCOUNT,
    PDM_GITHUBREPOSITORY,
    PDM_GITHUBRELEASEASSET
}
