CREATE SEQUENCE TASK_ID_SEQ             	        START 1 INCREMENT 1;
CREATE SEQUENCE SHIFT_ID_SEQ             	        START 1 INCREMENT 1;
CREATE SEQUENCE SHIFTPERSON_ID_SEQ             	  START 1 INCREMENT 1;
CREATE SEQUENCE ACCOMMODATION_ID_SEQ              START 1 INCREMENT 1;
CREATE SEQUENCE SUITE_ID_SEQ                      START 1 INCREMENT 1;
CREATE SEQUENCE DEPARTMENTPERSON_ID_SEQ           START 1 INCREMENT 1;
CREATE SEQUENCE OTHER_INFO_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE BED_ID_SEQ                        START 1 INCREMENT 1;
CREATE SEQUENCE PENDINGREASON_ID_SEQ              START 1 INCREMENT 1;

