BEGIN TRANSACTION;

SET SEARCH_PATH = EMM;


ALTER TABLE PLM_BOM DROP CONSTRAINT plm_bom_item_fkey;

UPDATE PLM_BOM SET item =
    (SELECT item_master
        FROM PLM_ITEMREVISION
            WHERE PLM_BOM.item = PLM_ITEMREVISION.item_id);

ALTER TABLE PLM_BOM ADD CONSTRAINT plm_bom_item_fkey FOREIGN KEY (ITEM) REFERENCES PLM_ITEM ON DELETE CASCADE;
ALTER TABLE PLM_BOM ADD CONSTRAINT plm_bom_as_released_revision_fkey FOREIGN KEY (as_released_revision) REFERENCES PLM_ITEMREVISION ON DELETE CASCADE;


COMMIT;