/* Begin enums */

DO $$
DECLARE
	enumTypes TEXT[];
BEGIN

enumTypes := ARRAY [
    'BID',
    'PROJECT',
    'WBS',
    'FILE',
    'FOLDER',
    'DOCUMENT',
    'BOQ',
    'BOQITEM',
    'COMMENT',
    'TAG',
    'SUPPLIER',
    'RFQ',
    'RFQITEM',
    'MACHINETYPE',
    'MATERIALTYPE',
    'MANPOWERTYPE',
    'TODOLIST',
    'TODOITEM',
    'MESSAGE',
    'REQUISITION',
    'CUSTOMER',
    'ROLE',
    'ISSUE',
    'ITEM',
    'ITEMTYPE',
    'STORE',
    'PROJECTTASK',
    'MEETING',
    'SITE',
    'MATERIAL',
    'MACHINE',
    'MANPOWER',
    'ISSUEITEM',
    'RECEIVE',
    'RECEIVEITEM',
    'LOAN',
    'STOCKMOVEMENT',
    'LOANISSUEITEM',
    'LOANRETRUNITEMRECEIVED',
    'LOANRETURNITEMISSUED',
    'LOANRECEIVEITEM',
    'SCRAPREQUEST',
    'SCRAPREQUESTITEM',
    'CUSTOM_REQUISITION',
    'CUSTOM_PURCHASEORDER',
    'CUSTOM_RECEIVECHALAN',
    'CUSTOM_ISSUECHALAN',
    'CUSTOM_ROADCHALAN',
    'CUSTOM_INDENT',
    'ROADCHALLAN',
    'ROADCHALLANITEM',
    'STOCKRETURN',
    'STOCKRETURNITEM',
    'TASKPROBLEM',
    'PROBLEM',
    'CONTRACTOR',
    'WORKORDER',
    'WORKORDERITEM',
    'MATERIALRECEIVETYPE',
    'MATERIALISSUETYPE',
    'ISWORKFLOWDEFINITION',
	  'ISWORKFLOWDEFINITIONSTATUS',
	  'ISWORKFLOWDEFINITIONTRANSITION',
	  'ISWORKFLOWDEFINITIONSTART',
	  'ISWORKFLOWDEFINITIONFINISH',
	  'ISWORKFLOWDEFINITIONTERMINATE',
	  'ISWORKFLOW',
	  'ISWORKFLOWSTATUS',
	  'ISWORKFLOWTRANSITION',
	  'ISWORKFLOWSTART',
	  'ISWORKFLOWFINISH',
	  'ISWORKFLOWTERMINATE',
	  'WORKFLOWTYPE'
];

CREATE FUNCTION createEnums(eArray TEXT[]) RETURNS VOID LANGUAGE PLPGSQL VOLATILE
    AS $f$
        DECLARE
            t TEXT;
        BEGIN
            FOREACH t IN ARRAY eArray LOOP
                EXECUTE 'ALTER TYPE OBJECT_TYPE ADD VALUE ' || quote_literal(t);
            END loop;
        END;
    $f$;


PERFORM createEnums(enumTypes);

CREATE TYPE INVENTORYRECORD_TYPE AS ENUM (
    'INWARD',
    'OUTWARD'
);

CREATE TYPE DOC_TYPE AS ENUM (
    'DEFAULT',
    'DRAWING'
 );

CREATE TYPE ISSUE_PRIORITY AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH'
);

CREATE TYPE ISSUE_STATUS AS ENUM (
    'NEW',
    'ASSIGNED',
    'INPROGRESS',
    'CLOSED'
);

CREATE TYPE TASK_STATUS AS ENUM (
    'NEW',
    'ASSIGNED',
    'INPROGRESS',
    'FINISHED',
    'INSPECTED'
);

CREATE TYPE MOVEMENT_TYPE AS ENUM (
    'RECEIVED',
    'ISSUED',
    'LOANISSUED',
    'LOANRECEIVED',
    'LOANRETURNITEMRECEIVED',
    'LOANRETURNITEMISSUED',
    'ALLOCATED',
    'OPENINGBALANCE',
    'RETURNED'
);

CREATE TYPE RECEIVING_TYPE AS ENUM (
    'PURCHASE',
    'TRANSFER'
);

CREATE TYPE ISSUING_TYPE AS ENUM (
    'CONSUME',
    'TRANSFER'
);

CREATE TYPE PERMISSION_LEVEL AS ENUM(
    'PERSON',
    'ROLE'
);

CREATE TYPE RESOURCE_TYPE AS ENUM(
   'MATERIALTYPE',
   'MANPOWERTYPE',
   'MACHINETYPE',
   'ROLE'
);

CREATE TYPE ATTACHMENT_TYPE AS ENUM(
   'FILE',
   'DOCUMENT',
   'DRAWING'
);

CREATE TYPE LOAN_STATUS AS ENUM(
    'PENDING',
    'RETURNED'
);

CREATE TYPE REQUISITION_STATUS AS ENUM (
    'NEW',
    'INPROGRESS',
    'APPROVED'
);

CREATE TYPE STOCKRETURN_STATUS AS ENUM (
    'NEW',
    'INPROGRESS',
    'APPROVED'
);

CREATE TYPE PURCHASEORDER_STATUS AS ENUM (
    'NEW',
    'APPROVED'
);

CREATE TYPE INDENT_STATUS AS ENUM (
    'NEW',
    'APPROVED'
);

CREATE TYPE INSPECTION_RESULT AS ENUM (
    'ACCEPTED',
    'REJECTED'
);

CREATE TYPE WORKORDER_STATUS AS ENUM (
    'PENDING',
    'FINISHED'
);

END $$;


/* End enums */

