/* Begin procurement management tables */
CREATE TABLE IS_BOQ (
    BOQ_ID                      INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL DEFAULT 'New Group',
    FOREIGN KEY (BOQ_ID)        REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_BIDBOQ (
    BOQ_ID                      INTEGER             NOT NULL PRIMARY KEY,
    BID                         INTEGER             NOT NULL REFERENCES IS_BID (BID_ID) ON DELETE CASCADE,
    FOREIGN KEY (BOQ_ID)        REFERENCES          IS_BOQ (BOQ_ID)
);

CREATE TABLE IS_PROJECTBOQ (
    BOQ_ID                      INTEGER             NOT NULL PRIMARY KEY,
    PROJECT                     INTEGER             NOT NULL REFERENCES IS_PROJECT (PROJECT_ID),
    FOREIGN KEY (BOQ_ID)        REFERENCES          IS_BOQ (BOQ_ID) ON DELETE CASCADE
);

CREATE TABLE IS_BOQITEM (
    ITEM_ID                     INTEGER             NOT NULL PRIMARY KEY,
    BOQ                         INTEGER             NOT NULL REFERENCES IS_BOQ (BOQ_ID) ON DELETE CASCADE,
    BOQNAME                     TEXT                NOT NULL,
    ITEMNAME                    TEXT                NOT NULL,
    PROJECT                     INTEGER             NOT NULL REFERENCES IS_PROJECT(PROJECT_ID) ON DELETE CASCADE,
    ITEM_NUMBER                 TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    UNITS                       TEXT                NOT NULL,
    UNIT_PRICE                  DOUBLE  PRECISION   NOT NULL DEFAULT 0,
    UNIT_COST                   DOUBLE  PRECISION   NOT NULL DEFAULT 0,
    RESTYPE                     RESOURCE_TYPE       ,
    ACTUALCOST                  DOUBLE PRECISION    NOT NULL DEFAULT 0,
    QUANTITY                    DOUBLE PRECISION    NOT NULL DEFAULT 0,
    ISSAVEDITEM                 BOOLEAN             NOT NULL DEFAULT FALSE,
    NOTES                       TEXT                ,
    UNIQUE(BOQNAME,PROJECT,ITEM_NUMBER)
);

CREATE TABLE IS_BOQACTUALCOST (
    ROWID                     INTEGER             NOT NULL PRIMARY KEY,
    BOQITEM                   INTEGER             NOT NULL REFERENCES IS_BOQITEM(ITEM_ID) ON DELETE CASCADE,
    COSTNAME                  TEXT                NOT NULL,
    COST                      DOUBLE PRECISION    NOT NULL DEFAULT 0
);

CREATE TABLE IS_SUPPLIER (
    SUPPLIER_ID                 INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    CONTACT_PERSON              TEXT                ,
    CONTACT_PHONE               TEXT                ,
    FOREIGN KEY (SUPPLIER_ID)   REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_SUPPLIERADDRESS (
    SUPPLIER                    INTEGER             NOT NULL REFERENCES IS_SUPPLIER (SUPPLIER_ID) ON DELETE CASCADE,
    ADDRESS                     INTEGER             NOT NULL REFERENCES ADDRESS (ADDRESS_ID) ON DELETE CASCADE,
    UNIQUE (SUPPLIER, ADDRESS)
);

CREATE TABLE IS_RFQ (
    RFQ_ID                      INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                NOT NULL,
    FOREIGN KEY (RFQ_ID)        REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_BIDRFQ (
    RFQ_ID                      INTEGER             NOT NULL PRIMARY KEY,
    BID                         INTEGER             NOT NULL REFERENCES IS_BID (BID_ID) ON DELETE CASCADE,
    FOREIGN KEY (RFQ_ID)        REFERENCES          IS_RFQ (RFQ_ID) ON DELETE CASCADE
);

CREATE TABLE IS_PROJECTRFQ (
    RFQ_ID                      INTEGER             NOT NULL PRIMARY KEY,
    PROJECT                     INTEGER             NOT NULL REFERENCES IS_PROJECT (PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (RFQ_ID)        REFERENCES          IS_RFQ (RFQ_ID) ON DELETE CASCADE
);

CREATE TABLE IS_RFQITEM (
    RFQITEM_ID                  INTEGER             NOT NULL PRIMARY KEY,
    RFQ_ID                      INTEGER             NOT NULL REFERENCES IS_RFQ (RFQ_ID) ON DELETE CASCADE,
    ITEM_NAME                   TEXT                NOT NULL,
    DESCRIPTION                 TEXT                NOT NULL,
    UNITS                       TEXT                NOT NULL,
    QUANTITY                    DOUBLE PRECISION    NOT NULL DEFAULT 0
);

CREATE TABLE IS_RFQSENTTO (
    ROWID                       INTEGER            NOT NULL PRIMARY KEY,
    RFQ                         INTEGER             NOT NULL REFERENCES IS_RFQ (RFQ_ID) ON DELETE CASCADE,
    SUPPLIER                    INTEGER             NOT NULL REFERENCES IS_SUPPLIER (SUPPLIER_ID) ON DELETE CASCADE,
    SENT_ON                     TIMESTAMP           ,
    SENT_BY                     INTEGER             REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    SENT_TO                     INTEGER             REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE IS_RFQRESPONSE (
    ROWID                       INTEGER             NOT NULL PRIMARY KEY,
    RFQ                         INTEGER             NOT NULL REFERENCES IS_RFQ (RFQ_ID) ON DELETE CASCADE,
    SUPPLIER                    INTEGER             NOT NULL REFERENCES IS_SUPPLIER (SUPPLIER_ID) ON DELETE CASCADE,
    RESPONSE_DATE               TIMESTAMP           NOT NULL
);

CREATE TABLE IS_RFQRESPONSEITEM (
    ROWID                       INTEGER             NOT NULL PRIMARY KEY,
    RESPONSE                 	 INTEGER             NOT NULL REFERENCES IS_RFQRESPONSE (ROWID) ON DELETE CASCADE,
    SUPPLIER                    INTEGER             NOT NULL REFERENCES IS_SUPPLIER (SUPPLIER_ID) ON DELETE CASCADE,
    ITEM                        INTEGER             NOT NULL REFERENCES IS_RFQITEM (RFQITEM_ID) ON DELETE CASCADE,
    PRICE                       DOUBLE PRECISION    NOT NULL DEFAULT 0
);

CREATE TABLE IS_MATERIAL (
    ITEM_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PICTURE                     BYTEA               ,
    IS_ACTIVE                   BOOLEAN             NOT NULL,
    UNITS                       VARCHAR(50)         NOT NULL,
    CURRENT_INVENTORY           DOUBLE PRECISION    NOT NULL DEFAULT 0.0,
    FOREIGN KEY (ITEM_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_REQUISITIONREQUEST (
    REQUEST_ID                  INTEGER             NOT NULL PRIMARY KEY,
    FOREIGN KEY (REQUEST_ID)    REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_REQUISITIONAPPROVAL (
    ROWID                       INTEGER             NOT NULL PRIMARY KEY,
    REQUISITION                 INTEGER             NOT NULL REFERENCES IS_REQUISITIONREQUEST (REQUEST_ID) ON DELETE CASCADE,
    PERSON                      INTEGER             NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    APPROVED                    BOOLEAN             NOT NULL DEFAULT FALSE
);

CREATE TABLE IS_REQUISITIONITEMLIST (
    ROWID                       INTEGER             NOT NULL PRIMARY KEY,
    REQUISITION                 INTEGER             NOT NULL REFERENCES IS_REQUISITIONREQUEST (REQUEST_ID) ON DELETE CASCADE,
    ITEM                        INTEGER             NOT NULL REFERENCES IS_BOQITEM (ITEM_ID) ON DELETE CASCADE,
    QUANTITY                    DOUBLE PRECISION    NOT NULL DEFAULT 0
);

/* Begin inventory & stores schema */

CREATE TABLE IS_ITEMTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_ITEMTYPE (TYPE_ID) ON DELETE CASCADE,
    RESOURCE_TYPE               RESOURCE_TYPE       ,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE

);

CREATE TABLE IS_ITEMTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    ITEM_TYPE                     INTEGER           NOT NULL REFERENCES IS_ITEMTYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

/*Types*/

CREATE TABLE IS_MATERIALTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_MATERIALTYPE (TYPE_ID) ON DELETE CASCADE,
    MATERIALNUMBER_SOURCE       INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MACHINETYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_MACHINETYPE (TYPE_ID) ON DELETE CASCADE,
    MACHINENUMBER_SOURCE        INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MANPOWERTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_MANPOWERTYPE (TYPE_ID) ON DELETE CASCADE,
    MANPOWERNUMBER_SOURCE       INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MATERIALRECEIVETYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_MATERIALRECEIVETYPE (TYPE_ID) ON DELETE CASCADE,
    RECEIVENUMBER_SOURCE        INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MATERIALISSUETYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_MATERIALISSUETYPE (TYPE_ID) ON DELETE CASCADE,
    ISSUENUMBER_SOURCE          INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MANPOWERTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    ITEM_TYPE                     INTEGER           NOT NULL REFERENCES IS_MANPOWERTYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MACHINETYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    ITEM_TYPE                     INTEGER           NOT NULL REFERENCES IS_MACHINETYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MATERIALTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    ITEM_TYPE                     INTEGER           NOT NULL REFERENCES IS_MATERIALTYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MATERIALRECEIVETYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    ITEM_TYPE                     INTEGER           NOT NULL REFERENCES IS_MATERIALRECEIVETYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MATERIALISSUETYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    ITEM_TYPE                     INTEGER           NOT NULL REFERENCES IS_MATERIALISSUETYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_MATERIALITEM (
    ITEM_ID                     INTEGER             NOT NULL PRIMARY KEY,
    ITEM_TYPE                   INTEGER             NOT NULL REFERENCES IS_MATERIALTYPE(TYPE_ID) ON DELETE CASCADE,
    ITEM_NAME                   TEXT                NOT NULL,
    ITEM_NUMBER                 TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    ACTIVE                      BOOLEAN             NOT NULL DEFAULT FALSE,
    UNITS                       TEXT                NOT NULL DEFAULT 'Each',
    UNIT_COST                   DOUBLE PRECISION    NOT NULL DEFAULT 0,
    UNIT_PRICE                  DOUBLE PRECISION    NOT NULL DEFAULT 0,
    PICTURE                     BYTEA               ,
    FOREIGN KEY (ITEM_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    UNIQUE (ITEM_NUMBER)
);

CREATE TABLE IS_MACHINEITEM (
    ITEM_ID                     INTEGER             NOT NULL PRIMARY KEY,
    ITEM_TYPE                   INTEGER             NOT NULL REFERENCES IS_MACHINETYPE(TYPE_ID) ON DELETE CASCADE,
    ITEM_NAME                   TEXT                NOT NULL,
    ITEM_NUMBER                 TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    ACTIVE                      BOOLEAN             NOT NULL DEFAULT FALSE,
    UNITS                       TEXT                NOT NULL DEFAULT 'Each',
    UNIT_COST                   DOUBLE PRECISION    NOT NULL DEFAULT 0,
    UNIT_PRICE                  DOUBLE PRECISION    NOT NULL DEFAULT 0,
    PICTURE                     BYTEA               ,
    FOREIGN KEY (ITEM_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    UNIQUE (ITEM_NUMBER)
);

CREATE TABLE IS_MANPOWERITEM (
    ITEM_ID                     INTEGER             NOT NULL PRIMARY KEY,
    ITEM_TYPE                   INTEGER             NOT NULL REFERENCES IS_MANPOWERTYPE(TYPE_ID) ON DELETE CASCADE,
    PERSON                      INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE ,
    ITEM_NUMBER                 TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    ACTIVE                      BOOLEAN             NOT NULL DEFAULT FALSE,
    UNITS                       TEXT                NOT NULL DEFAULT 'Days',
    UNIT_COST                   DOUBLE PRECISION    NOT NULL DEFAULT 0,
    UNIT_PRICE                  DOUBLE PRECISION    NOT NULL DEFAULT 0,
    PICTURE                     BYTEA               ,
    FOREIGN KEY (ITEM_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    UNIQUE (ITEM_NUMBER)
);

CREATE TABLE IS_MATERIALITEMATTRIBUTE (
    ITEM                        INTEGER             NOT NULL REFERENCES IS_MATERIALITEM (ITEM_ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES IS_MATERIALTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM, ATTRIBUTE) REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF) ON DELETE CASCADE,
    UNIQUE (ITEM, ATTRIBUTE)
);

CREATE TABLE IS_MACHINEITEMATTRIBUTE (
    ITEM                        INTEGER             NOT NULL REFERENCES IS_MACHINEITEM (ITEM_ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES IS_MACHINETYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM, ATTRIBUTE) REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF) ON DELETE CASCADE,
    UNIQUE (ITEM, ATTRIBUTE)
);

CREATE TABLE IS_MANPOWERITEMATTRIBUTE (
    ITEM                        INTEGER             NOT NULL REFERENCES IS_MANPOWERITEM (ITEM_ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES IS_MANPOWERTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM, ATTRIBUTE) REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF) ON DELETE CASCADE,
    UNIQUE (ITEM, ATTRIBUTE)
);

/* End inventory and stores schema */


/* Begin subcontracts tables */
CREATE TABLE IS_CONTRACTOR (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    CONTACT                     INTEGER             NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    ACTIVE                      BOOLEAN             NOT NULL DEFAULT FALSE,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKORDER (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NUMBER                      TEXT                NOT NULL,
    CONTRACTOR                  INTEGER             NOT NULL REFERENCES IS_CONTRACTOR (ID) ON DELETE CASCADE,
    STATUS                      WORKORDER_STATUS    NOT NULL DEFAULT 'PENDING',
    PROJECT                     INTEGER             NOT NULL REFERENCES IS_PROJECT (PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKORDERITEM (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    WORK_ORDER                  INTEGER             NOT NULL REFERENCES IS_WORKORDER (ID) ON DELETE CASCADE,
    TASK                        INTEGER             NOT NULL REFERENCES IS_PROJECTTASK (TASK_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);
/* End subcontracts tables */

/* End procurement management tables */