CREATE TABLE IS_BIDMESSAGE (
    MESSAGE_ID                  INTEGER             NOT NULL PRIMARY KEY,
    BID                         INTEGER             NOT NULL REFERENCES IS_BID (BID_ID) ON DELETE CASCADE,
    FOREIGN KEY (MESSAGE_ID)    REFERENCES          MESSAGE (MESSAGE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_PROJECTMESSAGE (
    MESSAGE_ID                  INTEGER             NOT NULL PRIMARY KEY,
    PROJECT                     INTEGER             NOT NULL REFERENCES IS_PROJECT (PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (MESSAGE_ID)    REFERENCES          MESSAGE (MESSAGE_ID) ON DELETE CASCADE
);

CREATE TABLE IS_BIDMEETING (
    MEETING_ID                  INTEGER             NOT NULL PRIMARY KEY,
    BID                         INTEGER             NOT NULL REFERENCES IS_BID (BID_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEETING_ID)    REFERENCES          MEETING (MEETING_ID) ON DELETE CASCADE
);

CREATE TABLE IS_PROJECTMEETING (
    MEETING_ID                  INTEGER             NOT NULL PRIMARY KEY,
    PROJECT                     INTEGER             NOT NULL REFERENCES IS_PROJECT (PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEETING_ID)    REFERENCES          MEETING (MEETING_ID) ON DELETE CASCADE
);

CREATE TABLE IS_PROJECTUSERINBOX (
    PROJECTINBOX_ID             INTEGER         NOT NULL PRIMARY KEY,
    PROJECT_ID                  INTEGER         NOT NULL REFERENCES IS_PROJECT (PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROJECTINBOX_ID)   REFERENCES      USERINBOX (INBOX_ID) ON DELETE CASCADE
);


/* End collaboration tables */