CREATE TYPE WORKFLOW_STATUS_TYPE AS ENUM (
    'PENDING',
    'REVIEW',
    'RELEASED',
    'COMPLETE',
    'CANCELLED',
    'HOLD',
    'UNDEFINED'
);

CREATE TYPE WORKFLOW_ASSIGNMENT_TYPE AS ENUM (
    'APPROVER',
    'OBSERVER',
    'ACKNOWLEDGER'
);

CREATE TYPE APPROVER_VOTE AS ENUM (
    'APPROVE',
    'REJECT'
);

CREATE TYPE STATUS_FLAG AS ENUM (
    'UNASSIGNED',
    'INPROCESS',
    'COMPLETED'
);


/*ALTER TABLE IS_ECO ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE NOT NULL;
ALTER TABLE IS_MCO ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE NOT NULL;*/

CREATE TABLE IS_WORKFLOWTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES IS_WORKFLOWTYPE (TYPE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    WRFL_TYPE                     INTEGER           NOT NULL REFERENCES IS_WORKFLOWTYPE (TYPE_ID) ON DELETE CASCADE,
    SEQ                           INTEGER           ,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);


CREATE TABLE IS_WORKFLOWDEFINITION (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    WORKFLOW_TYPE               INTEGER             REFERENCES IS_WORKFLOWTYPE (TYPE_ID) ON DELETE CASCADE,
    DESCRIPTION                 TEXT,
    DIAGRAM                     TEXT,
    DIAGRAM_ID                  TEXT,
    ASSIGNABLE_TO               TEXT [],
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);


CREATE TABLE IS_WORKFLOWDEFINITIONSTATUS (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES IS_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    NAME                        TEXT          NOT NULL,
    DESCRIPTION                 TEXT,
    TYPE                        WORKFLOW_STATUS_TYPE NOT NULL,
    DIAGRAM_ID                  TEXT,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWDEFINITIONSTART (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWDEFINITIONFINISH (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWDEFINITIONTERMINATE (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE
);

ALTER TABLE IS_WORKFLOWDEFINITION ADD COLUMN START INTEGER REFERENCES IS_WORKFLOWDEFINITIONSTART(ID) ON DELETE CASCADE;
ALTER TABLE IS_WORKFLOWDEFINITION ADD COLUMN FINISH INTEGER REFERENCES IS_WORKFLOWDEFINITIONFINISH(ID) ON DELETE CASCADE;


CREATE TABLE IS_WORKFLOWDEFINITIONTRANSITION (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER NOT NULL REFERENCES IS_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    NAME                        TEXT,
    FROM_STATUS                 INTEGER NOT NULL REFERENCES IS_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE,
    TO_STATUS                   INTEGER NOT NULL REFERENCES IS_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE,
    DIAGRAM_ID                  TEXT,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOW (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    NAME                        TEXT    NOT NULL,
    DESCRIPTION                 TEXT,
    DIAGRAM                     TEXT,
    DIAGRAM_ID                  TEXT,
    STARTED                     BOOLEAN NOT NULL DEFAULT FALSE,
    STARTED_ON                  TIMESTAMP,
    FINISHED                    BOOLEAN NOT NULL DEFAULT FALSE,
    FINISHED_ON                 TIMESTAMP,
    ATTACHED_TO                 INTEGER,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWATTRIBUTE (
    WORKFLOW                    INTEGER             NOT NULL REFERENCES IS_WORKFLOW (ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES IS_WORKFLOWTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW, ATTRIBUTE)          REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (WORKFLOW, ATTRIBUTE)
);

CREATE TABLE IS_WORKFLOWSTATUS (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES IS_WORKFLOW (ID) ON DELETE CASCADE,
    NAME                        TEXT          NOT NULL,
    DESCRIPTION                 TEXT,
    TYPE                        WORKFLOW_STATUS_TYPE NOT NULL,
    DIAGRAM_ID                  TEXT,
    FLAG                        STATUS_FLAG NOT NULL DEFAULT 'UNASSIGNED',
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWSTATUSHISTORY (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES IS_WORKFLOW (ID) ON DELETE CASCADE,
    STATUS                      INTEGER       NOT NULL REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    TIMESTAMP                   TIMESTAMP     NOT NULL
);

CREATE TABLE IS_WORKFLOWSTART (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWFINISH (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWTERMINATE (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE
);

ALTER TABLE IS_WORKFLOW ADD COLUMN START INTEGER REFERENCES IS_WORKFLOWSTART(ID) ON DELETE CASCADE;
ALTER TABLE IS_WORKFLOW ADD COLUMN FINISH INTEGER REFERENCES IS_WORKFLOWFINISH(ID) ON DELETE CASCADE;
ALTER TABLE IS_WORKFLOW ADD COLUMN CURRENT_STATUS INTEGER REFERENCES IS_WORKFLOWSTATUS(ID) ON DELETE CASCADE;
ALTER TABLE is_TASK ADD COLUMN WORKFLOW INTEGER REFERENCES IS_WORKFLOW (ID) ON DELETE SET NULL;


CREATE TABLE IS_WORKFLOWTRANSITION (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER NOT NULL REFERENCES IS_WORKFLOW (ID) ON DELETE CASCADE,
    NAME                        TEXT,
    FROM_STATUS                 INTEGER NOT NULL REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    TO_STATUS                   INTEGER NOT NULL REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    DIAGRAM_ID                  TEXT,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWSTATUSASSIGNMENT (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    STATUS                      INTEGER NOT NULL REFERENCES IS_WORKFLOWSTATUS(ID) ON DELETE CASCADE,
    ASSIGNMENT_TYPE             WORKFLOW_ASSIGNMENT_TYPE NOT NULL,
    PERSON                      INTEGER NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    COMMENTS                    TEXT,
    LAST_NOTIFIED_ON            TIMESTAMP
);


CREATE TABLE IS_WORKFLOWSTATUSACTIONHISTORY (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES IS_WORKFLOW (ID) ON DELETE CASCADE,
    STATUS                      INTEGER       NOT NULL REFERENCES IS_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    ASSIGNMENT                  INTEGER       NOT NULL REFERENCES IS_WORKFLOWSTATUSASSIGNMENT(ID) ON DELETE CASCADE,
    ACTION                      TEXT          NOT NULL,
    TIMESTAMP                   TIMESTAMP     NOT NULL
);


CREATE TABLE IS_WORKFLOWSTATUSAPPROVER (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    VOTE                        APPROVER_VOTE,
    TIMESTAMP                   TIMESTAMP,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWSTATUSASSIGNMENT (ID) ON DELETE CASCADE
);


CREATE TABLE IS_WORKFLOWSTATUSOBSERVER (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWSTATUSASSIGNMENT (ID) ON DELETE CASCADE
);

CREATE TABLE IS_WORKFLOWSTATUSACKNOWLEDGER (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    ACKNOWLEDGED                BOOLEAN DEFAULT FALSE,
    TIMESTAMP                   TIMESTAMP,
    NOTE                        TEXT,
    FOREIGN KEY (ID)            REFERENCES IS_WORKFLOWSTATUSASSIGNMENT (ID) ON DELETE CASCADE
);
