/* Begin sequences */
CREATE SEQUENCE WBS_ID_SEQ                      START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMERTYPE_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE RFQITEM_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE TODOITEM_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE PORTFOLIO_ID_SEQ                START 1 INCREMENT 1;
CREATE SEQUENCE BOQ_ID_SEQ                		  START 1 INCREMENT 1;
CREATE SEQUENCE ISSUETYPE_ID_SEQ             	  START 1 INCREMENT 1;
CREATE SEQUENCE ISSUEPRIORITY_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE MESSAGE_ID_SEQ            		  START 1 INCREMENT 1;
CREATE SEQUENCE PROJECTPERSON_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE ISPERSONROLE_ID_SEQ            	START 1 INCREMENT 1;
CREATE SEQUENCE OBJECTPERMISSION_ID_SEQ         START 1 INCREMENT 1;
CREATE SEQUENCE IS_SITESTORE_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE IS_TASKFILES_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE BOQ_ACTUALCOST_ID_SEQ           START 1 INCREMENT 1;
CREATE SEQUENCE ITEMNUMBER_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE TOPINVENTORY_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE TOPSITE_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE TOPSTOCKMOVEMENT_ID_SEQ         START 1 INCREMENT 1;
CREATE SEQUENCE TASKCOMPLETIONHISTORY_ID_SEQ    START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMINDENTITEM_ID_SEQ         START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMISSUEITEM_ID_SEQ          START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMPURCHASEORDERITEM_ID_SEQ  START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMRECEIVEITEM_ID_SEQ        START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMREQUISITIONITEM_ID_SEQ    START 1 INCREMENT 1;
CREATE SEQUENCE LINK_ID_SEQ                     START 1 INCREMENT 1;

CREATE SEQUENCE CUSTOMROADCHALANITEM_ID_SEQ     START 1 INCREMENT 1;
CREATE SEQUENCE TASK_IMAGE_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE PROJECTPERSONORGANIZATION_ID_SEQ         START 1 INCREMENT 1;
CREATE SEQUENCE PROJECTPERSONROLE_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE WORKFLOWSTATUSASSIGNMENT_ID_SEQ START 1 INCREMENT 1;
CREATE SEQUENCE IS_TASKCOMPLETIONRESOURCE_ID_SEQ START 1 INCREMENT 1;
/* End sequences */
