package com.cassinisys.plm.model.dto.print;

import com.cassinisys.platform.model.common.Person;
import com.cassinisys.plm.model.cm.*;
import com.cassinisys.plm.model.cm.dto.*;
import com.cassinisys.plm.model.dto.*;
import com.cassinisys.plm.model.mes.*;
import com.cassinisys.plm.model.mes.dto.BOPDto;
import com.cassinisys.plm.model.mes.dto.BOPRouteDto;
import com.cassinisys.plm.model.mfr.*;
import com.cassinisys.plm.model.mro.*;
import com.cassinisys.plm.model.mro.dto.WorkOrderDto;
import com.cassinisys.plm.model.pgc.*;
import com.cassinisys.plm.model.plm.PLMItem;
import com.cassinisys.plm.model.plm.dto.BomDto;
import com.cassinisys.plm.model.pm.*;
import com.cassinisys.plm.model.pqm.*;
import com.cassinisys.plm.model.pqm.dto.InspectionsDto;
import com.cassinisys.plm.model.pqm.dto.ObjectFileDto;
import com.cassinisys.plm.model.pqm.dto.ProblemReportsDto;
import com.cassinisys.plm.model.req.PLMProjectRequirementDocument;
import com.cassinisys.plm.model.rm.RequirementDeliverable;
import com.cassinisys.plm.model.rm.SpecificationDeliverable;
import lombok.Data;

import java.util.*;

@Data
public class PrintDTO {
    List<MROAssetSparePart> spareParts = new ArrayList<>();
    List<WorkOrderDto> maintenancePlans = new ArrayList<>();
    List<PLMVariance> mfrVarience = new ArrayList<>();
    Map<String, List<PrintAttributesDTO>> groupMasterAttributes = new HashMap<>();
    Map<String, List<PrintAttributesDTO>> groupRevisionAttributes = new HashMap<>();
    Map<String, List<ChangeAttributeDTO>> groupChangeAttributes = new HashMap<>();
    Map<String, List<QualityAttributeDTO>> groupQualityAttributes = new HashMap<>();
    List<ProblemReportsDto> ecrProblemReports;
    private String objectType;
    private PLMItem itemClass;
    private PLMItem item;
    private List<BomDto> plmBom = new LinkedList<>();
    private List<PrintAttributesDTO> itemMasterAttributes = new LinkedList<>();
    private List<PrintAttributesDTO> itemRevAttributes = new LinkedList<>();
    private List<PrintAttributesDTO> itemCustomAttributes = new LinkedList<>();
    private List<PrintAttributesDTO> itemCustomRevAttributes = new LinkedList<>();
    private List<PLMECO> changes = new LinkedList<>();
    private List<PLMECR> ecrs = new LinkedList<>();
    private List<PLMDCO> dcos = new LinkedList<>();
    private List<PLMDCR> dcrs = new LinkedList<>();
    private List<PQMProblemReport> itemPrs = new LinkedList<>();
    private List<PQMProblemReport> productPrs = new LinkedList<>();
    private List<PQMQCR> itemQcrs = new LinkedList<>();
    private List<InspectionsDto> itemInspections = new LinkedList<>();
    private List<ProjectItemsDto> itemProjects = new LinkedList<>();
    private List<RequirementDeliverable> itemReqs = new LinkedList<>();
    private List<PLMItemManufacturerPart> itemmParts = new ArrayList<>();
    private PLMECO eco;
    private List<ChangeAttributeDTO> changeTypeAttributes = new LinkedList<>();
    private List<QualityAttributeDTO> qualityTypeAttributes = new LinkedList<>();
    private List<PrintAttributesDTO> changeTypeCustomAttributes = new LinkedList<>();
    private List<PLMAffectedItem> changesAffectedItems = new LinkedList<>();
    private List<ECRDto> ecoChangeReqs = new LinkedList<>();
    private List<RelatedItemDto> relatedItems = new LinkedList<>();
    private PLMECR ecr;
    private List<ECRAffecteditemsDto> ecrAffectedItems = new LinkedList<>();
    private PLMDCR dcr;
    private List<DCRAffecteditemsDto> dcrAffectedItems = new LinkedList<>();
    private PLMDCO dco;
    private List<DCRDto> dcoChangeReqs = new LinkedList<>();
    private List<DCRAffecteditemsDto> dcoAffectedItems = new LinkedList<>();
    private PLMMCO mco;
    private List<MCOAffecteditemsDto> mcoAffectedItems = new LinkedList<>();
    private List<MCOProductAffectedItemDto> mcoAffectedMbom = new LinkedList<>();
    private List<PLMMCORelatedItem> mcoRelatedItems = new LinkedList<>();
    private PLMVariance variance;
    private List<VarianceAffectedItemDto> varianceAffectedItems = new LinkedList<>();
    private PQMInspection inspection;
    private PQMInspectionPlan inspectionPlan;
    private List<CheckListDTO> checkLists = new LinkedList<>();
    private PQMProblemReport problemReport;
    private PQMNCR pqmncr;
    private PQMQCR pqmqcr;
    private PQMPPAP pqmppap;
    private PQMSupplierAudit supplierAudit;
    private List<ProblemItemDto> problemItems = new LinkedList<>();
    private String qcrFor;
    private List<ProblemSourceDto> problemSources = new LinkedList<>();
    private PLMProject project;
    private PLMProgram program;
    private List<Person> persons = new LinkedList<>();
    private List<PLMProgramResource> resources = new LinkedList<>();
    private List<WBSDto> projectPlan = new LinkedList<>();
    private PLMProjectDeliverableDto deliverables;
    private List<PLMProjectItemReference> projectRefItems = new LinkedList<>();
    private List<PLMProjectRequirementDocument> projectRequirements = new LinkedList<>();
    private List<PQMQCRCAPA> pqmqcrcapas = new LinkedList<>();
    private List<PLMDeliverable> itemDeliverables = new ArrayList<>();
    private List<PLMGlossaryDeliverable> glossaryDeliverables = new ArrayList<>();
    private List<SpecificationDeliverable> specificationDeliverables = new ArrayList<>();
    private List<RequirementDeliverable> requirementDeliverables = new ArrayList<>();
    private MESPlant plant;
    private MESAssemblyLine assemblyLine;
    private MESWorkCenter workCenter;
    private MESMachine machine;
    private MESEquipment equipment;
    private MESInstrument instrument;
    private MESTool tool;
    private MESJigsFixture jigsFixture;
    private MESMaterial material;
    private MESManpower manpower;
    private MESShift shift;
    private MESOperation operation;
    private MROAsset asset;
    private MROMeter meter;
    private MROSparePart sparePart;
    private MROMaintenancePlan maintenancePlan;
    private List<MROMaintenanceOperation> maintenanceOperations = new ArrayList<>();
    private MROWorkRequest workRequest;
    private MROWorkOrder workOrder;
    private List<MROWorkOrderOperation> workOrderOperations = new ArrayList<>();
    private List<MROWorkOrderResource> workOrderResources = new ArrayList<>();
    private List<MROWorkOrderPart> workOrderParts = new ArrayList<>();
    private PGCSubstance substance;
    private PGCSpecification specification;
    private PGCDeclaration declaration;
    private List<PGCSpecificationSubstance> substanceList = new ArrayList<>();
    private List<PGCDeclarationSpecification> declarationSpecifications = new ArrayList<>();
    private List<PGCDeclarationPart> declarationParts = new ArrayList<>();
    private List<PGCItemSpecification> itemSpecifications = new ArrayList<>();
    private PLMManufacturer manufacturer;
    private PLMManufacturerPart manufacturerPart;
    private PLMSupplier supplier;
    private List<PLMManufacturerPart> mfrParts = new ArrayList<>();
    private List<PLMItemManufacturerPart> whereUsedItems = new ArrayList<>();
    private List<PLMMCO> mfrChanges = new ArrayList<>();
    private List<PQMQCR> qcrs = new ArrayList<>();
    private List<PQMNCR> ncrs = new ArrayList<>();
    private List<PLMSupplierContact> contacts = new ArrayList<>();
    private List<PLMSupplierPart> supParts = new ArrayList<>();
    private BomComplianceReport bomComplianceReport;
    private ObjectFileDto fileDto;
    private List<PLMChangeFile> changeFiles;
    private List<PQMSupplierAuditPlan> auditPlans;
    private List<MESWorkCenter> workCenters;
    private List<ProgramProjectDto> programProjects = new LinkedList<>();
    private List<BOPRouteDto> bopRoutes = new LinkedList<>();
    private BOPDto bopDto;
}