CREATE SEQUENCE RUN_ID_SEQ             	             START 1 INCREMENT 1;
CREATE SEQUENCE INPUTPARAM_ID_SEQ                    START 1 INCREMENT 1;
CREATE SEQUENCE OUTPUTPARAM_ID_SEQ                    START 1 INCREMENT 1;
CREATE SEQUENCE INPUTPARAMVALUE_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE OUTPUTPARAMEXPECTEDVALUE_ID_SEQ      START 1 INCREMENT 1;
CREATE SEQUENCE OUTPUTPARAMACTUALVALUE_ID_SEQ        START 1 INCREMENT 1;
CREATE SEQUENCE IM_TESTNOTIFICATION_ID_GEN_SEQ       START 1 INCREMENT 1;
CREATE SEQUENCE TEST_EXECUTION_ID_SEQ                START 1 INCREMENT 1;
CREATE SEQUENCE RC_EXECUTION_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE RCOUTPUTPARAM_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE RUNEXECUTION_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE RUNSCHEDULE_ID_SEQ                   START 1 INCREMENT 1;
CREATE SEQUENCE RCOUTPUTPARAMEXPECTEDVALUE_ID_SEQ    START 1 INCREMENT 1;
CREATE SEQUENCE RCINPUTPARAMVALUE_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE RUNINPUTPARAM_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE RUNOUTPUTPARAM_ID_SEQ                START 1 INCREMENT 1;
CREATE SEQUENCE RUNINPUTPARAMVALUE_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE RUNOUTPUTPARAMEXPECTEDVALUE_ID_SEQ   START 1 INCREMENT 1;
CREATE SEQUENCE RUNOUTPUTPARAMACTUALVALUE_ID_SEQ     START 1 INCREMENT 1;
CREATE SEQUENCE RUNOUTPUTLOG_ID_SEQ                  START 1 INCREMENT 1;




