CREATE TYPE WORKFLOW_STATUS_TYPE AS ENUM (
    'START',
    'NORMAL',
    'RELEASED',
    'REJECTED',
    'FINISH',
    'TERMINATE',
    'UNDEFINED'
);

CREATE TYPE WORKFLOW_ASSIGNMENT_TYPE AS ENUM (
    'APPROVER',
    'OBSERVER',
    'ACKNOWLEDGER'
);

CREATE TYPE APPROVER_VOTE AS ENUM (
    'APPROVE',
    'REJECT'
);

CREATE TYPE STATUS_FLAG AS ENUM (
    'UNASSIGNED',
    'INPROCESS',
    'TERMINATED',
    'ONHOLD',
    'COMPLETED'
);


ALTER TABLE PLM_ECO ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE NOT NULL;
ALTER TABLE PLM_MCO ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE NOT NULL;
ALTER TABLE PLM_DCO ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE;
ALTER TABLE PLM_CHANGE_REQUEST ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE;

CREATE TABLE PLM_WORKFLOWTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES PLM_WORKFLOWTYPE (TYPE_ID) ON DELETE CASCADE,
    NUMBER_SOURCE               INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    LIFECYCLE                   INTEGER             REFERENCES PLM_LIFECYCLE (ID) ON DELETE CASCADE,
    REVISION_SEQUENCE           INTEGER             REFERENCES LOV (LOV_ID) ON DELETE CASCADE,
    ASSIGNABLE                  TEXT                ,
    ASSIGNED_TYPE               INTEGER             ,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    WRFL_TYPE                     INTEGER           NOT NULL REFERENCES PLM_WORKFLOWTYPE (TYPE_ID) ON DELETE CASCADE,
    SEQ                           INTEGER           ,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWDEFINITIONMASTER (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NUMBER                      TEXT                NOT NULL,
    INSTANCES                   INTEGER             DEFAULT 0,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWDEFINITION (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    MASTER                      INTEGER             NOT NULL REFERENCES PLM_WORKFLOWDEFINITIONMASTER (ID) on delete cascade,
    NAME                        TEXT                NOT NULL,
    WORKFLOW_TYPE               INTEGER             REFERENCES PLM_WORKFLOWTYPE (TYPE_ID) ON DELETE CASCADE,
    DESCRIPTION                 TEXT,
    REVISION                    TEXT                NOT NULL,
    STATUS                      INTEGER             NOT NULL REFERENCES PLM_LIFECYCLEPHASE (ID),
    IS_RELEASED                 BOOLEAN             NOT NULL DEFAULT FALSE,
    RELEASED_DATE               TIMESTAMP           ,
    DIAGRAM                     TEXT,
    DIAGRAM_ID                  TEXT,
    ASSIGNABLE_TO               TEXT [],
    INSTANCES                   INTEGER            DEFAULT 0,
    FOREIGN KEY (ID)            REFERENCES         CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

ALTER TABLE PLM_WORKFLOWDEFINITIONMASTER ADD COLUMN LATEST_REVISION INTEGER REFERENCES PLM_WORKFLOWDEFINITION(ID) ON DELETE CASCADE;
ALTER TABLE PLM_WORKFLOWDEFINITIONMASTER ADD COLUMN LATEST_RELEASED_REVISION INTEGER REFERENCES PLM_WORKFLOWDEFINITION(ID) ON DELETE CASCADE;

CREATE TABLE PLM_WORKFLOWDEFINITIONSTATUS (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES PLM_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    NAME                        TEXT          NOT NULL,
    DESCRIPTION                 TEXT,
    TYPE                        WORKFLOW_STATUS_TYPE NOT NULL,
    DIAGRAM_ID                  TEXT,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWACTIVITY_FORM_FIELDS (
    ID                              INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOWACTIVITY                INTEGER       NOT NULL REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)                REFERENCES    OBJECTTYPEATTRIBUTE(ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWDEFINITIONSTART (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWDEFINITIONFINISH (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWDEFINITIONTERMINATE (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE
);

ALTER TABLE PLM_WORKFLOWDEFINITION ADD COLUMN START INTEGER REFERENCES PLM_WORKFLOWDEFINITIONSTART(ID) ON DELETE CASCADE;
ALTER TABLE PLM_WORKFLOWDEFINITION ADD COLUMN FINISH INTEGER REFERENCES PLM_WORKFLOWDEFINITIONFINISH(ID) ON DELETE CASCADE;


CREATE TABLE PLM_WORKFLOWDEFINITIONTRANSITION (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER NOT NULL REFERENCES PLM_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    NAME                        TEXT,
    FROM_STATUS                 INTEGER NOT NULL REFERENCES PLM_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE,
    TO_STATUS                   INTEGER NOT NULL REFERENCES PLM_WORKFLOWDEFINITIONSTATUS (ID) ON DELETE CASCADE,
    DIAGRAM_ID                  TEXT,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOW (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    WORKFLOW_REVISION           INTEGER NOT NULL REFERENCES PLM_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    NAME                        TEXT    NOT NULL,
    DESCRIPTION                 TEXT,
    DIAGRAM                     TEXT,
    DIAGRAM_ID                  TEXT,
    STARTED                     BOOLEAN NOT NULL DEFAULT FALSE,
    STARTED_ON                  TIMESTAMP,
    FINISHED                    BOOLEAN NOT NULL DEFAULT FALSE,
    FINISHED_ON                 TIMESTAMP,
    CANCELLED                   BOOLEAN NOT NULL DEFAULT FALSE,
    CANCELLED_ON                TIMESTAMP,
    ONHOLD                      BOOLEAN NOT NULL DEFAULT FALSE,
    ONHOLD_ON                   TIMESTAMP,
    ATTACHED_TO                 INTEGER REFERENCES CASSINI_OBJECT(OBJECT_ID) ON DELETE  CASCADE,
    ATTACHED_TO_TYPE            OBJECT_TYPE,
    HOLD_BY                     INTEGER REFERENCES PERSON (PERSON_ID),
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    UNIQUE (ATTACHED_TO, ATTACHED_TO_TYPE)
);

CREATE TABLE PLM_WORKFLOWATTRIBUTE (
    WORKFLOW                    INTEGER             NOT NULL REFERENCES PLM_WORKFLOW (ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES PLM_WORKFLOWTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOW, ATTRIBUTE)          REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (WORKFLOW, ATTRIBUTE)
);

CREATE TABLE PLM_WORKFLOWSTATUS (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES PLM_WORKFLOW (ID) ON DELETE CASCADE,
    NAME                        TEXT          NOT NULL,
    DESCRIPTION                 TEXT,
    TYPE                        WORKFLOW_STATUS_TYPE NOT NULL,
    DIAGRAM_ID                  TEXT,
    FLAG                        STATUS_FLAG NOT NULL DEFAULT 'UNASSIGNED',
    ITERATION                   INTEGER       DEFAULT 0,
    TRANSITIONED_FROM           INTEGER       REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE SET NULL,
    STARTED_TIMESTAMP           TIMESTAMP     ,
    FINISHED_TIMESTAMP          TIMESTAMP     ,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWACTIVITY_FORMDATA (
    WORKFLOWSTATUS              INTEGER             NOT NULL REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES PLM_WORKFLOWACTIVITY_FORM_FIELDS (ID) ON DELETE CASCADE,
    FOREIGN KEY (WORKFLOWSTATUS, ATTRIBUTE)         REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (WORKFLOWSTATUS, ATTRIBUTE)
);

CREATE TABLE PLM_WORKFLOWSTATUSHISTORY (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES PLM_WORKFLOW (ID) ON DELETE CASCADE,
    STATUS                      INTEGER       NOT NULL REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    TIMESTAMP                   TIMESTAMP     NOT NULL,
    HOLD                        BOOLEAN       ,
    UNHOLD                      BOOLEAN       ,
    DEMOTED                     BOOLEAN       ,
    ASSIGNMENTS                 TEXT          ,
    NOTES                       TEXT
);

CREATE TABLE PLM_WORKFLOWSTART (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWFINISH (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWTERMINATE (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE
);

ALTER TABLE PLM_WORKFLOW ADD COLUMN START INTEGER REFERENCES PLM_WORKFLOWSTART(ID) ON DELETE CASCADE;
ALTER TABLE PLM_WORKFLOW ADD COLUMN FINISH INTEGER REFERENCES PLM_WORKFLOWFINISH(ID) ON DELETE CASCADE;
ALTER TABLE PLM_WORKFLOW ADD COLUMN CURRENT_STATUS INTEGER REFERENCES PLM_WORKFLOWSTATUS(ID) ON DELETE CASCADE;
ALTER TABLE PLM_ITEMREVISION ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_MANUFACTURER ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_MANUFACTURERPART ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_ECR ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_ECO ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_DCR ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_DCO ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_MCO ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_VARIANCE ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE PLM_VARIANCE ADD COLUMN STATUS_TYPE WORKFLOW_STATUS_TYPE;
ALTER TABLE PLM_NPR ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;
ALTER TABLE CUSTOM_OBJECT ADD COLUMN WORKFLOW INTEGER REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL;

CREATE TABLE PLM_WORKFLOWTRANSITION (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER NOT NULL REFERENCES PLM_WORKFLOW (ID) ON DELETE CASCADE,
    NAME                        TEXT,
    FROM_STATUS                 INTEGER NOT NULL REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    TO_STATUS                   INTEGER NOT NULL REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    DIAGRAM_ID                  TEXT,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWSTATUSASSIGNMENT (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    ITERATION                   INTEGER       DEFAULT 0,
    STATUS                      INTEGER NOT NULL REFERENCES PLM_WORKFLOWSTATUS(ID) ON DELETE CASCADE,
    ASSIGNMENT_TYPE             WORKFLOW_ASSIGNMENT_TYPE NOT NULL,
    PERSON                      INTEGER NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    COMMENTS                    TEXT,
    LAST_NOTIFIED_ON            TIMESTAMP
);


CREATE TABLE PLM_WORKFLOWSTATUSACTIONHISTORY (
    ID                          INTEGER       NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER       NOT NULL REFERENCES PLM_WORKFLOW (ID) ON DELETE CASCADE,
    STATUS                      INTEGER       NOT NULL REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE CASCADE,
    ASSIGNMENT                  INTEGER       NOT NULL REFERENCES PLM_WORKFLOWSTATUSASSIGNMENT(ID) ON DELETE CASCADE,
    ACTION                      TEXT          NOT NULL,
    TIMESTAMP                   TIMESTAMP     NOT NULL
);


CREATE TABLE PLM_WORKFLOWSTATUSAPPROVER (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    VOTE                        APPROVER_VOTE,
    TIMESTAMP                   TIMESTAMP,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWSTATUSASSIGNMENT (ID) ON DELETE CASCADE
);


CREATE TABLE PLM_WORKFLOWSTATUSOBSERVER (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    TIMESTAMP                   TIMESTAMP,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWSTATUSASSIGNMENT (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWSTATUSACKNOWLEDGER (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    ACKNOWLEDGED                BOOLEAN DEFAULT FALSE,
    TIMESTAMP                   TIMESTAMP,
    NOTE                        TEXT,
    FOREIGN KEY (ID)            REFERENCES PLM_WORKFLOWSTATUSASSIGNMENT (ID) ON DELETE CASCADE
);

CREATE TYPE USER_TASK_STATUS AS ENUM (
    'PENDING',
    'FINISHED',
    'CANCELLED'
);

CREATE TABLE PLM_USERTASK (
    ID                          INTEGER NOT NULL PRIMARY KEY,
    ASSIGNED_TO                 INTEGER NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    SOURCE                      INTEGER NOT NULL REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    SOURCE_TYPE                 OBJECT_TYPE NOT NULL,
    CONTEXT                     INTEGER NOT NULL REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    CONTEXT_TYPE                OBJECT_TYPE NOT NULL,
    STATUS                      USER_TASK_STATUS NOT NULL DEFAULT 'PENDING',
    DUE_DATE                    DATE,
    FINISHED_ON                 TIMESTAMP,
    CANCELLED_ON                TIMESTAMP,
    FOREIGN KEY (ID)            REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

ALTER TABLE PLM_CHANGE ADD COLUMN WORKFLOW_STATUS INTEGER REFERENCES PLM_WORKFLOWSTATUS (ID) ON DELETE SET NULL;

CREATE TABLE PLM_WORKFLOW_REVISION_HISTORY (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER                 NOT NULL REFERENCES PLM_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    OLD_STATUS                  INTEGER                 REFERENCES PLM_LIFECYCLEPHASE (ID),
    NEW_STATUS                  INTEGER                 REFERENCES PLM_LIFECYCLEPHASE (ID),
    TIMESTAMP                   TIMESTAMP               NOT NULL,
    UPDATED_BY                  INTEGER                 NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_WORKFLOWDEFINITION_EVENT (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER                 NOT NULL REFERENCES PLM_WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
    EVENT_TYPE                  TEXT                    ,
    ACTIVITY                    INTEGER                 REFERENCES PLM_WORKFLOWDEFINITIONSTATUS (ID),
    ACTION_TYPE                 TEXT                    ,
    ACTION_DATA                 TEXT
);

CREATE TABLE PLM_WORKFLOW_EVENT (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    WORKFLOW                    INTEGER                 NOT NULL REFERENCES PLM_WORKFLOW (ID) ON DELETE CASCADE,
    EVENT_TYPE                  TEXT                    ,
    ACTIVITY                    INTEGER                 REFERENCES PLM_WORKFLOWSTATUS (ID),
    ACTION_TYPE                 TEXT                    ,
    ACTION_DATA                 TEXT
);
