CREATE TYPE REQUIREMENT_APPROVAL_STATUS AS ENUM (
    'NONE',
    'APPROVED',
    'REJECTED',
    'REVIEWED'
);
CREATE TABLE PLM_REQUIREMENTOBJECTTYPE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    NUMBER_SOURCE               INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTOBJECTTYPEATTRIBUTE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    TYPE                        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTOBJECTTYPE(ID) ON DELETE CASCADE,
    SEQUENCE                    INTEGER             NOT NULL DEFAULT 1,
    FOREIGN KEY (ID)            REFERENCES          OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTTYPE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    PARENT                      INTEGER             REFERENCES PLM_REQUIREMENTOBJECTTYPE(ID) ON DELETE CASCADE,
    LIFECYCLE                   INTEGER             REFERENCES PLM_LIFECYCLE (ID) ON DELETE CASCADE,
    TABS                        TEXT[]              ,
    REVISION_SEQUENCE           INTEGER             REFERENCES LOV (LOV_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECTTYPE (ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTTYPE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    PARENT                      INTEGER             REFERENCES PLM_REQUIREMENTTYPE(ID) ON DELETE CASCADE,
    PRIORITY_LIST               INTEGER             REFERENCES LOV (LOV_ID) ON DELETE SET NULL,
    LIFECYCLE                   INTEGER             REFERENCES PLM_LIFECYCLE (ID) ON DELETE CASCADE,
    TABS                        TEXT[]              ,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECTTYPE (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_REQUIREMENTOBJECT(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTOBJECTATTRIBUTE(
    OBJECT                      INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTOBJECT (ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTOBJECTTYPEATTRIBUTE (ID) ON DELETE CASCADE,
    FOREIGN KEY (OBJECT, ATTRIBUTE)                 REFERENCES OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (OBJECT, ATTRIBUTE)
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTTEMPLATE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    TYPE                        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTTYPE (ID) ON DELETE CASCADE,
    LIFECYCLE_PHASE             INTEGER             NOT NULL REFERENCES PLM_LIFECYCLEPHASE (ID),
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECT (id) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTTEMPLATEELEMENT(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    TEMPLATE                    INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTTEMPLATE(ID) ON DELETE CASCADE,
    TYPE                        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTTYPE(ID) ON DELETE CASCADE,
    PARENT                      INTEGER             REFERENCES PLM_REQUIREMENTDOCUMENTTEMPLATEELEMENT(ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENT(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    TYPE                        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTTYPE(ID) ON DELETE CASCADE,
    TEMPLATE                    INTEGER             REFERENCES PLM_REQUIREMENTDOCUMENTTEMPLATE(ID) ON DELETE CASCADE,
    NUMBER                      TEXT                NOT NULL,
    LATEST_REVISION             INTEGER             ,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECT (ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTREVISION(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    MASTER                      INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENT(ID) ON DELETE CASCADE,
    REVISION                    TEXT                NOT NULL,
    LIFECYCLE_PHASE             INTEGER             NOT NULL REFERENCES PLM_LIFECYCLEPHASE (ID),
    LATEST                      BOOLEAN             NOT NULL DEFAULT FALSE,
    OWNER                       INTEGER             NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE SET NULL,
    NOTES                       TEXT                ,
    WORKFLOW                    INTEGER             REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECT (ID) ON DELETE CASCADE
);
CREATE TABLE PLM_PROJECT_REQUIREMENTDOCUMENT(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    PROJECT                     INTEGER             NOT NULL REFERENCES PLM_PROJECT(ID) ON DELETE CASCADE,
    REQ_DOCUMENT                INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION(ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENT(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    SEQUENCE                    INTEGER             NOT NULL DEFAULT 1,
    PATH                        TEXT                NOT NULL,
    TYPE                        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTTYPE(ID) ON DELETE CASCADE,
    NUMBER                      TEXT                NOT NULL,
    LATEST_VERSION              INTEGER             ,
    IGNORE_FOR_RELEASE          BOOLEAN             DEFAULT FALSE,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECT (ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTVERSION(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    MASTER                      INTEGER             NOT NULL REFERENCES PLM_REQUIREMENT(ID) ON DELETE CASCADE,
    DOCUMENT                    INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION(ID) ON DELETE CASCADE,
    PARENT                      INTEGER             REFERENCES PLM_REQUIREMENTVERSION(ID) ON DELETE CASCADE,
    VERSION                     INTEGER             NOT NULL DEFAULT 1,
    LATEST                      BOOLEAN             NOT NULL DEFAULT FALSE,
    PRIORITY                    TEXT                NOT NULL,
    LIFECYCLE_PHASE             INTEGER             NOT NULL REFERENCES PLM_LIFECYCLEPHASE (ID),
    PLANNED_FINISH_DATE         DATE                ,
    ACTUAL_FINISH_DATE          DATE                ,
    ASSIGNED_TO                 INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE SET NULL,
    NOTES                       TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PLM_REQUIREMENT_ITEM(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT_VERSION         INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTVERSION(ID) ON DELETE CASCADE,
    ITEM                        INTEGER             NOT NULL REFERENCES PLM_ITEMREVISION(ITEM_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_REQUIREMENTDOCUMENTFILE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    DOCUMENT                    INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTFILE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT                 INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTVERSION(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTOBJECTRELATEDITEM(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    OBJECT_TYPE                 OBJECT_TYPE         NOT NULL,
    OBJECT_ID                   INTEGER             NOT NULL
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTRELATEDITEM(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    DOCUMENT                    INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECTRELATEDITEM (ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTRELATEDITEM(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT                 INTEGER             NOT NULL REFERENCES PLM_REQUIREMENT(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECTRELATEDITEM (ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDELIVERABLE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT                 INTEGER             NOT NULL REFERENCES PLM_REQUIREMENT(ID) ON DELETE CASCADE,
    ITEM                        INTEGER             NOT NULL REFERENCES PLM_ITEMREVISION(ITEM_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTREVIEWER(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT_VERSION         INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTVERSION(ID) ON DELETE CASCADE,
    REVIEWER                    INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
    APPROVER                    BOOLEAN             NOT NULL DEFAULT FALSE,
    VOTE                        REQUIREMENT_APPROVAL_STATUS NOT NULL DEFAULT 'NONE',
    VOTE_TIMESTAMP              TIMESTAMP           ,
    NOTES                       TEXT
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTREVIEWER(
    ID                            INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT_DOCUMENT_REVISION INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION(ID) ON DELETE CASCADE,
    REVIEWER                      INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
    APPROVER                      BOOLEAN             NOT NULL DEFAULT FALSE,
    VOTE                          REQUIREMENT_APPROVAL_STATUS NOT NULL DEFAULT 'NONE',
    VOTE_TIMESTAMP                TIMESTAMP           ,
    NOTES                         TEXT
);
CREATE TABLE PLM_REQUIREMENTTEMPLATE(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    SEQUENCE                    INTEGER             NOT NULL DEFAULT 1,
    PATH                        TEXT                NOT NULL,
    DOCUMENT_TEMPLATE           INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTTEMPLATE(ID) ON DELETE CASCADE,
    TYPE                        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTTYPE(ID) ON DELETE CASCADE,
    PARENT                      INTEGER             REFERENCES PLM_REQUIREMENTTEMPLATE(ID) ON DELETE CASCADE,
    PRIORITY                    TEXT                NOT NULL,
    LIFECYCLE_PHASE             INTEGER             NOT NULL REFERENCES PLM_LIFECYCLEPHASE (ID),
    ASSIGNED_TO                 INTEGER             REFERENCES PERSON(PERSON_ID) ON DELETE SET NULL,
    FOREIGN KEY (ID)            REFERENCES          PLM_REQUIREMENTOBJECT (id) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTTEMPLATEREVIEWER(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    DOCUMENT_TEMPLATE           INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTTEMPLATE(ID) ON DELETE CASCADE,
    REVIEWER                    INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
    APPROVER                    BOOLEAN             NOT NULL DEFAULT FALSE
);
CREATE TABLE PLM_REQUIREMENTTEMPLATEREVIEWER(
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    REQUIREMENT_TEMPLATE        INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTTEMPLATE(ID) ON DELETE CASCADE,
    REVIEWER                    INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
    APPROVER                    BOOLEAN             NOT NULL DEFAULT FALSE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENTREVISIONSTATUSHISTORY (
  ROWID                         INTEGER             NOT NULL PRIMARY KEY,
  DOCUMENTREVISION              INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION (ID) ON DELETE CASCADE,
  OLD_STATUS                    INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
  NEW_STATUS                    INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
  TIMESTAMP                     TIMESTAMP           NOT NULL,
  UPDATED_BY                    INTEGER             NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTVERSIONSTATUSHISTORY (
  ROWID                         INTEGER             NOT NULL PRIMARY KEY,
  REQUIREMENT_VERSION           INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTVERSION (ID) ON DELETE CASCADE,
  OLD_STATUS                    INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
  NEW_STATUS                    INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
  TIMESTAMP                     TIMESTAMP           NOT NULL,
  NOTES                         TEXT                ,
  UPDATED_BY                    INTEGER             NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE
);
CREATE TABLE PLM_REQUIREMENTDOCUMENT_CHILDREN(
    ID                            INTEGER             NOT NULL PRIMARY KEY,
    DOCUMENT                      INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTDOCUMENTREVISION(ID) ON DELETE CASCADE,
    REQUIREMENT_VERSION           INTEGER             NOT NULL REFERENCES PLM_REQUIREMENTVERSION(ID) ON DELETE CASCADE,
    PARENT                        INTEGER             REFERENCES PLM_REQUIREMENTVERSION(ID) ON DELETE CASCADE,
    WORKFLOW                      INTEGER             REFERENCES PLM_WORKFLOW (ID) ON DELETE SET NULL,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);