DROP FUNCTION IF EXISTS createEnums(TEXT[]);
CREATE FUNCTION createEnums(eArray TEXT[])
RETURNS VOID AS
$$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY eArray LOOP
        EXECUTE 'ALTER TYPE OBJECT_TYPE ADD VALUE ' || quote_literal(t);
    END loop;
END;
$$
LANGUAGE PLPGSQL;

DROP FUNCTION IF EXISTS createGroupPermission(INTEGER, TEXT, TEXT, TEXT, TEXT);
CREATE FUNCTION createGroupPermission(groupId INTEGER,ot TEXT ,st TEXT,p TEXT,a TEXT)
RETURNS VOID AS
$$
DECLARE
    permissionId INTEGER;
BEGIN
  IF st IS NULL AND a IS NULL THEN
    SELECT PERMISSION_ID INTO permissionId FROM SECURITY_PERMISSION WHERE OBJECT_TYPE = ot AND SUB_TYPE IS NULL AND PRIVILEGE =p AND ATTRIBUTE IS NULL;
  ELSEIF st IS NOT NULL AND a IS NOT NULL THEN
    SELECT PERMISSION_ID INTO permissionId FROM SECURITY_PERMISSION WHERE OBJECT_TYPE = ot AND SUB_TYPE = st AND PRIVILEGE =p AND ATTRIBUTE = a;
  ELSEIF st IS NULL AND a IS NOT NULL THEN
    SELECT PERMISSION_ID INTO permissionId FROM SECURITY_PERMISSION WHERE OBJECT_TYPE = ot AND SUB_TYPE IS NULL AND PRIVILEGE =p AND ATTRIBUTE = a;
  ELSE
    SELECT PERMISSION_ID INTO permissionId FROM SECURITY_PERMISSION WHERE OBJECT_TYPE = ot AND SUB_TYPE = st AND PRIVILEGE =p AND ATTRIBUTE IS NULL;
  END IF;
  INSERT INTO GROUP_SECURITY_PERMISSION (PERSONGROUP, SECURITY_PERMISSION)  VALUES (groupId, permissionId);
END;
$$
LANGUAGE PLPGSQL;

DROP FUNCTION IF EXISTS createPersonGroup(INTEGER, TEXT, TEXT,INTEGER, BOOLEAN, BOOLEAN);
CREATE FUNCTION createPersonGroup(groupId INTEGER,n TEXT,d TEXT,p INTEGER,a BOOLEAN,e BOOLEAN)
RETURNS VOID AS
$$
BEGIN
     INSERT INTO PERSONGROUP (GROUP_ID, NAME, DESCRIPTION,PARENT,IS_ACTIVE,EXTERNAL)
        VALUES (groupId, n, d, p,a, e);
END;
$$
LANGUAGE PLPGSQL;

DROP FUNCTION IF EXISTS getPersonGroupId(TEXT);
CREATE FUNCTION getPersonGroupId(groupName TEXT)
  RETURNS INT AS
  $$
  DECLARE
    groupId integer;
BEGIN
      SELECT GROUP_ID into groupId FROM PERSONGROUP WHERE NAME = groupName;
      RETURN groupId;
END;
$$
LANGUAGE PLPGSQL;

DROP FUNCTION IF EXISTS createDefaultProfileGroup(INTEGER, TEXT);
CREATE FUNCTION createDefaultProfileGroup(gId INTEGER,n TEXT)
  RETURNS VOID AS
  $$
DECLARE
  profileId INTEGER;
BEGIN
     SELECT PROFILE_ID INTO profileId FROM PROFILE WHERE name = n;
     UPDATE PERSONGROUP  SET PROFILE = profileId WHERE group_id = gId;
END;
$$
LANGUAGE PLPGSQL;






