/* Begin enums */

DO $$
DECLARE
	enumTypes TEXT[];
	pdmEnumTypes TEXT[];
	mesEnumTypes TEXT[];
	mroEnumTypes TEXT[];
	pgcEnumTypes TEXT[];
	requirementEnumTypes TEXT[];
BEGIN

enumTypes := ARRAY [
    'ITEMTYPE',
    'ITEM',
    'CHANGETYPE',
    'CHANGE',
    'BOMITEM',
    'FILE',
    'MANUFACTURERTYPE',
    'MANUFACTURER',
    'MANUFACTURERPARTTYPE',
    'MANUFACTURERPART',
    'FOLDER',
    'LIBRARY'
    'SAVEDSEARCH',
    'ITEMREVISION',
    'PLMWORKFLOWDEFINITION',
    'PLMWORKFLOWDEFINITIONSTATUS',
    'PLMWORKFLOWDEFINITIONTRANSITION',
    'PLMWORKFLOWDEFINITIONSTART',
    'PLMWORKFLOWDEFINITIONFINISH',
    'PLMWORKFLOWDEFINITIONTERMINATE',
    'PLMWORKFLOW',
    'PLMWORKFLOWSTATUS',
    'PLMWORKFLOWTRANSITION',
    'PLMWORKFLOWSTART',
    'PLMWORKFLOWFINISH',
    'PLMWORKFLOWTERMINATE',
    'WORKFLOWTYPE',
    'SHAREDOBJECT',

    'PROJECT',
    'PROJECTPHASEELEMENT',
    'PROJECTACTIVITY',
    'PROJECTTASK',
    'PROJECTMILESTONE',
    'PROJECTPROGRAM',
    'RELATIONSHIP',
    'RELATEDITEM',

    'TEMPLATE',
    'TEMPLATEPHASE',
    'TEMPLATEACTIVITY',
    'TEMPLATEMILESTONE',
    'TEMPLATETASK',

    'SPECIFICATIONTYPE',
    'REQUIREMENTTYPE',
    'SPECIFICATION',
    'REQUIREMENT',
    'RMRELATIONSHIP',
    'RMRELATEDITEM',
    'SPECSECTION',
    'SPECREQUIREMENT',

    'GLOSSARY',
    'GLOSSARYENTRY',
    'TERMINOLOGY',
    'TERMINOLOGYENTRY',
    'BOMCONFIGURATION',

    'ECR',
    'ECO',
    'DCR',
    'DCO',
    'MCO',
    'DEVIATION',
    'WAIVER',
    'ECRTYPE',
    'ECOTYPE',
    'DCRTYPE',
    'DCOTYPE',
    'MCOTYPE',
    'DEVIATIONTYPE',
    'WAIVERTYPE',
    'ECRAFFECTEDITEM',
    'DCRAFFECTEDITEM',
    'DCOAFFECTEDITEM',
    'MCOAFFECTEDITEM',
    'VARIANCEAFFECTEDITEM',
    'VARIANCEAFFECTEDMATERIAL',
    'VARIANCE',
    'ITEMMCO',
    'OEMPARTMCO',

    'QUALITY',
    'QUALITY_TYPE',
    'PR',
    'PRTYPE',
    'CUSTOMER',
    'SUPPLIER',
    'INSPECTIONPLANTYPE',
    'INSPECTIONPLAN',
    'PRODUCTINSPECTIONPLAN',
    'MATERIALINSPECTIONPLAN',
    'INSPECTIONPLANREVISION',
    'INSPECTIONPLANCHECKLIST',
    'INSPECTIONCHECKLIST',
    'INSPECTIONRELEATEDITEM',
    'INSPECTION',
    'INSPECTIONTYPE',
    'ITEMINSPECTION',
    'MATERIALINSPECTION',
    'PROBLEMREPORT',
    'PROBLEMREPORTTYPE',
    'NCR',
    'NCRTYPE',
    'NCRPROBLEMITEM',
    'QCR',
    'QCRTYPE',
    'QCRCAPA',
    'QCRAUDIT',
    'QCRPROBLEMITEM',
    'QCRPROBLEMMATERIAL',
    'PRPROBLEMITEM',
    'NCRRELATEDMATERIAL',
    'NCRPROBLEMMATERIAL',
    'PRRELATEDITEM',
    'QCRRELATEDITEM',
    'QCRRELATEDMATERIAL',
    'USERTASK',
    'PMOBJECTTYPE',
    'SUPPLIERTYPE',
    'MFRSUPPLIER',
    'PLMNPR',
    'DOCUMENT',
    'OBJECTDOCUMENT',
    'PPAP',
    'PPAPTYPE',
    'MFRPARTINSPECTIONREPORT',
    'PPAPCHECKLIST',
    'SUPPLIERAUDIT',
    'SUPPLIERAUDITTYPE',
    'SUPPLIERAUDITPLAN',
    'MBOMTYPE',
    'BOPTYPE',
    'PROGRAM',
    'PROGRAMFILE',
    'PROGRAMTEMPLATE',
    'REQUIREMENTDOCUMENTCHILDREN'
];

pdmEnumTypes := ARRAY [
    'PDM_ASSEMBLY',
    'PDM_PART',
    'PDM_DRAWING',
    'PDM_DRAWINGTEMPLATE',
    'PDM_REVISIONMASTER',
    'PDM_CONFIGURATION',
    'PDM_BOMOCCURRENCE',
    'PDM_FILE',
    'PDM_FILEVERSION',
    'PDM_FOLDER',
    'PDM_VAULT',
    'PDM_COMMIT',
    'PDM_GITHUBACCOUNT',
    'PDM_GITHUBREPOSITORY',
    'PDM_GITHUBRELEASEASSET'
];

mesEnumTypes := ARRAY [
    'MESOBJECTTYPE',
    'PLANTTYPE',
    'WORKCENTERTYPE',
    'MACHINETYPE',
    'TOOLTYPE',
    'PRODUCTIONRESOURCETYPE',
    'MATERIALTYPE',
    'PRODUCTIONORDERTYPE',
    'SERVICEORDERTYPE',
    'JIGFIXTURETYPE',
    'OPERATIONTYPE',
    'MANPOWERTYPE',
    'EQUIPMENTTYPE',
    'INSTRUMENTTYPE',
    'ASSEMBLYLINETYPE',
    'MESOBJECT',
    'PLANT',
    'WORKCENTER',
    'MACHINE',
    'TOOL',
    'PRODUCTIONRESOURCE',
    'PRODUCTIONORDER',
    'SERVICEORDER',
    'OPERATION',
    'MATERIAL',
    'JIGFIXTURE',
    'MANPOWER',
    'EQUIPMENT',
    'INSTRUMENT',
    'SHIFT',
    'ASSEMBLYLINE',
    'MBOM',
    'BOP',
    'MBOMREVISION',
    'MBOMITEM',
    'PHANTOM',
    'MBOMFILE',
    'BOPPLAN',
    'BOPREVISION',
    'BOPROUTEOPERATION',
    'PRODUCTIONORDERITEM',
    'MBOMINSTANCE',
    'MBOMINSTANCEITEM',
    'ITEMINSTANCE',
    'BOPINSTANCE',
    'BOPINSTANCEROUTEOPERATION'
];


mroEnumTypes := ARRAY [
    'SPAREPARTTYPE',
    'ASSETTYPE',
    'METERTYPE',
    'WORKREQUESTTYPE',
    'WORKORDERTYPE',
    'MROOBJECT',
    'MROASSET',
    'MROPLANTASSET',
    'MROWORKCENETRASSET',
    'MROMACHINEASSET',
    'MROEQUIPMENTASSET',
    'MROINSTRMENTASSET',
    'MROTOOLASSET',
    'MROJIGFIXTUREASSET',
    'MROMETER',
    'MROSPAREPART',
    'MROWORKREQUEST',
    'MROWORKORDER',
    'MROMAINTENANCEPLAN'
];

pgcEnumTypes := ARRAY [
    'PGCOBJECTTYPE',
    'PGCOBJECT',
    'PGCSUBSTANCETYPE',
    'PGCSUBSTANCEGROUPTYPE',
    'PGCDECLARATIONTYPE',
    'PGCSPECIFICATIONTYPE',
    'PGCMATERIAL',
    'PGCSUBSTANCE',
    'PGCSUBSTANCEGROUP',
    'PGCDECLARATION',
    'PGCSPECIFICATION'
];

requirementEnumTypes := ARRAY [
    'REQUIREMENTDOCUMENTTYPE',
    'REQUIREMENTDOCUMENT',
    'REQUIREMENTDOCUMENTREVISION',
    'REQUIREMENTDOCUMENTTEMPLATE',
    'REQUIREMENTTEMPLATE'
];

PERFORM createEnums(enumTypes);
PERFORM createEnums(pdmEnumTypes);
PERFORM createEnums(mesEnumTypes);
PERFORM createEnums(mroEnumTypes);
PERFORM createEnums(pgcEnumTypes);
PERFORM createEnums(requirementEnumTypes);


CREATE TYPE ECO_VOTE AS ENUM (
    'APPROVE',
    'REJECT'
);

CREATE TYPE CHANGE_TYPE AS ENUM (
    'ECR',
    'ECO',
    'DCR',
    'DCO',
    'MCO',
    'DEVIATION',
    'WAIVER'
);


CREATE  TYPE MANUFACTURERPART_STATUS AS ENUM (
    'ACTIVE',
    'OBSOLETE',
    'ALTERNATE',
    'PREFERRED'
);

CREATE TYPE LIFECYCLE_PHASE_TYPE AS ENUM (
    'PRELIMINARY',
    'REVIEW',
    'APPROVED',
    'RELEASED',
    'OBSOLETE',
    'CANCELLED'
);

CREATE  TYPE SHARE_TYPE AS ENUM (
    'GROUP',
    'PERSON'
);

CREATE  TYPE SHARE_PERMISSION AS ENUM (
    'READ',
    'WRITE'
);

CREATE TYPE GLOSSARY_ENTRY_EDIT_STATUS AS ENUM (
    'NONE',
    'ACCEPTED',
    'REJECTED'
);

CREATE TYPE SPEC_ELEMENT_TYPE AS ENUM (
    'SECTION',
    'REQUIREMENT'
);

CREATE TYPE REQUIREMENT_STATUS AS ENUM (
    'NONE',
    'PENDING',
    'FINISHED'
);

CREATE TYPE REQUIREMENT_EDIT_STATUS AS ENUM (
    'NEW',
    'REJECTED',
    'ACCEPTED',
    'FINAL'
);
CREATE TYPE FOLDER_TYPE AS ENUM (
    'PUBLIC',
    'PRIVATE'
);

CREATE TYPE VOTE_TYPE AS ENUM (
    'NONE',
    'APPROVED',
    'REJECTED'
);

CREATE TYPE ITEM_CLASS AS ENUM (
    'PRODUCT',
    'ASSEMBLY',
    'PART',
    'DOCUMENT',
    'OTHER'
);

CREATE TYPE REVISION_CREATION_TYPE AS ENUM (
    'WORKFLOW_START',
    'ACTIVITY_COMPLETION'
);

CREATE TYPE MAKE_OR_BUY AS ENUM (
    'MAKE',
    'BUY'
);

CREATE TYPE MES_TYPE AS ENUM (
    'PLANTTYPE',
    'WORKCENTERTYPE',
    'MACHINETYPE',
    'TOOLTYPE',
    'PRODUCTIONRESOURCETYPE',
    'PRODUCTIONORDERTYPE',
    'SERVICEORDERTYPE',
    'OPERATIONTYPE',
    'MATERIALTYPE',
    'JIGFIXTURETYPE',
    'MANPOWERTYPE',
    'EQUIPMENTTYPE',
    'INSTRUMENTTYPE',
    'SPAREPARTTYPE',
    'ASSEMBLYLINETYPE'

);




END $$;
/* End enums */
