CREATE TABLE PLM_MANUFACTURERTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES PLM_MANUFACTURERTYPE (TYPE_ID) ON DELETE CASCADE,
    LIFECYCLE                   INTEGER             REFERENCES PLM_LIFECYCLE (ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_MANUFACTURERTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    MFR_TYPE                      INTEGER           NOT NULL REFERENCES PLM_MANUFACTURERTYPE (TYPE_ID) ON DELETE CASCADE,
    SEQ                           INTEGER           ,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);


CREATE TABLE PLM_MANUFACTURERPARTTYPE (
    TYPE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES PLM_MANUFACTURERPARTTYPE (TYPE_ID) ON DELETE CASCADE,
    LIFECYCLE                   INTEGER             REFERENCES PLM_LIFECYCLE (ID) ON DELETE CASCADE,
    FOREIGN KEY (TYPE_ID)       REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_MANUFACTURERPARTTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    MFRPART_TYPE                  INTEGER           NOT NULL REFERENCES PLM_MANUFACTURERPARTTYPE (TYPE_ID) ON DELETE CASCADE,
    SEQ                           INTEGER           ,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_MANUFACTURER (
    MFR_ID                  INTEGER             NOT NULL PRIMARY KEY,
    NAME                    TEXT                NOT NULL,
    MFR_TYPE                INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERTYPE (TYPE_ID) ON DELETE CASCADE,
    DESCRIPTION             TEXT                ,
    PHONE_NUMBER            TEXT                ,
    CONTACT_PERSON          TEXT                ,
    LIFECYCLE_PHASE         INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
    FOREIGN KEY (MFR_ID)    REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);


CREATE TABLE PLM_MANUFACTURERATTRIBUTE (
    MANUFACTURER                INTEGER             NOT NULL REFERENCES PLM_MANUFACTURER (MFR_ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANUFACTURER, ATTRIBUTE)           REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (MANUFACTURER, ATTRIBUTE)
);

CREATE TABLE PLM_MANUFACTURERFILE (
    FILE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    MANUFACTURER                INTEGER             NOT NULL REFERENCES PLM_MANUFACTURER (MFR_ID) ON DELETE CASCADE,
    FOREIGN KEY (FILE_ID)       REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_MANUFACTURERPART (
    MFRPART_ID              INTEGER             NOT NULL PRIMARY KEY,
    MFRPART_TYPE            INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERPARTTYPE (TYPE_ID) ON DELETE CASCADE,
    MFRPART_NUMBER          TEXT                NOT NULL,
    MFRPART_NAME            TEXT                NOT NULL,
    DESCRIPTION             TEXT                ,
    STATUS                  TEXT                NOT NULL,
    MANUFACTURER            INTEGER             NOT NULL REFERENCES PLM_MANUFACTURER (MFR_ID) ON DELETE CASCADE,
    LIFECYCLE_PHASE         INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
    THUMBNAIL               BYTEA               ,
    SERIALIZED              BOOLEAN             NOT NULL DEFAULT TRUE,
    FOREIGN KEY (MFRPART_ID)    REFERENCES      CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_MANUFACTURERPARTATTRIBUTE (
    MFR_PART                    INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERPARTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MFR_PART, ATTRIBUTE)     REFERENCES          OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (MFR_PART, ATTRIBUTE)
);

CREATE TABLE PLM_MANUFACTURERPARTFILE (
    FILE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    MANUFACTURER_PART           INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    FOREIGN KEY (FILE_ID)       REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_MFRPART_INSPECTIONREPORT (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    MANUFACTURER_PART           INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    REVISION                    TEXT                NOT NULL,
    LIFECYCLE_PHASE             INTEGER             NOT NULL REFERENCES PLM_LIFECYCLEPHASE (ID),
    FOREIGN KEY (ID)            REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_ITEMMANUFACTURERPART (
    ROWID                       INTEGER             NOT NULL PRIMARY KEY,
    ITEM                        INTEGER             NOT NULL REFERENCES PLM_ITEMREVISION (ITEM_ID) ON DELETE CASCADE,
    MANUFACTURER_PART           INTEGER             NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    STATUS                      TEXT                ,
    NOTES                       TEXT                ,
    MODIFIED_DATE               TIMESTAMP           NOT NULL DEFAULT now(),
    UNIQUE (ITEM, MANUFACTURER_PART)
);

ALTER TABLE PLM_MCO_AFFECTEDITEM ADD COLUMN MATERIAL INTEGER NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE;
ALTER TABLE PLM_MCO_AFFECTEDITEM ADD COLUMN REPLACEMENT INTEGER REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE;
ALTER TABLE PLM_MCO_RELATEDITEM ADD COLUMN PART INTEGER REFERENCES PLM_MANUFACTURERPART(MFRPART_ID)ON DELETE CASCADE;

ALTER TABLE PLM_VARIANCE_AFFECTED_MATERIAL ADD COLUMN MATERIAL INTEGER NOT NULL REFERENCES PLM_MANUFACTURERPART(MFRPART_ID) ON DELETE CASCADE;
ALTER TABLE PLM_MANUFACTURER_MCO ADD COLUMN  PART INTEGER REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE;
CREATE TABLE PLM_MANUFACTURER_PART_HISTORY (
  ID                          INTEGER              NOT NULL PRIMARY KEY ,
  AFFECTED_PART               INTEGER              NOT NULL REFERENCES PLM_MCO_AFFECTEDITEM(ID) ON DELETE CASCADE,
  ITEM_SOURCE                 INTEGER []
);

/* Supplier tables */
CREATE TABLE PLM_SUPPLIER_TYPE (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES PLM_SUPPLIER_TYPE (ID) ON DELETE CASCADE,
    LIFECYCLE                   INTEGER             REFERENCES PLM_LIFECYCLE (ID) ON DELETE CASCADE,
    AUTONUMBER_SOURCE           INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_SUPPLIERTYPEATTRIBUTE (
    ATTRIBUTE_ID                  INTEGER           NOT NULL PRIMARY KEY,
    TYPE                          INTEGER           NOT NULL REFERENCES PLM_SUPPLIER_TYPE (ID) ON DELETE CASCADE,
    SEQ                           INTEGER           ,
    FOREIGN KEY (ATTRIBUTE_ID)    REFERENCES        OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_SUPPLIER (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    TYPE                        INTEGER                 NOT NULL REFERENCES PLM_SUPPLIER_TYPE(ID) ON DELETE CASCADE,
    NAME                        TEXT                    NOT NULL,
    NUMBER                      TEXT                    ,
    DESCRIPTION                 TEXT                    ,
    ADDRESS                     TEXT                    ,
    CITY                        TEXT                    ,
    COUNTRY                     TEXT                    ,
    POSTAL_CODE                 TEXT                    ,
    PHONE_NUMBER                TEXT                    ,
    MOBILE_NUMBER               TEXT                    ,
    FAX_NUMBER                  TEXT                    ,
    EMAIL                       TEXT                    ,
    WEBSITE                     TEXT                    ,
    LIFECYCLE_PHASE             INTEGER             REFERENCES PLM_LIFECYCLEPHASE (ID),
    FOREIGN KEY (ID)            REFERENCES              CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

ALTER TABLE CUSTOM_OBJECT ADD COLUMN SUPPLIER            INTEGER         REFERENCES PLM_SUPPLIER(ID) ON DELETE CASCADE;

CREATE TABLE PLM_SUPPLIERATTRIBUTE (
    SUPPLIER                    INTEGER             NOT NULL REFERENCES PLM_SUPPLIER (ID) ON DELETE CASCADE,
    ATTRIBUTE                   INTEGER             NOT NULL REFERENCES PLM_SUPPLIERTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (SUPPLIER, ATTRIBUTE)               REFERENCES OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (SUPPLIER, ATTRIBUTE)
);

CREATE TABLE PLM_SUPPLIERFILE (
    FILE_ID                     INTEGER             NOT NULL PRIMARY KEY,
    SUPPLIER                    INTEGER             NOT NULL REFERENCES PLM_SUPPLIER (ID) ON DELETE CASCADE,
    FOREIGN KEY (FILE_ID)       REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);

CREATE TABLE PLM_SUPPLIER_CONTACT (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    SUPPLIER                    INTEGER                 NOT NULL REFERENCES PLM_SUPPLIER(ID) ON DELETE CASCADE,
    CONTACT                     INTEGER                 NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    ROLE                        TEXT                    ,
    ACTIVE                      BOOLEAN                 NOT NULL DEFAULT TRUE
);

CREATE TABLE PLM_SUPPLIER_PART (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    SUPPLIER                    INTEGER                 NOT NULL REFERENCES PLM_SUPPLIER(ID) ON DELETE CASCADE,
    PART                        INTEGER                 NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    PART_NUMBER                 TEXT                    NOT NULL,
    MODIFIED_DATE               TIMESTAMP           NOT NULL DEFAULT now()
);