CREATE TYPE BOS_ITEM_TYPE AS ENUM (
    'MATERIAL',
    'SUBSTANCE',
    'SUBSTANCEGROUP'
);

CREATE TYPE COMPOSITION_TYPE AS ENUM (
    'MATERIAL',
    'SUBSTANCE'
);

CREATE TYPE DECLARATION_STATUS AS ENUM (
    'OPEN',
    'SUBMITTED',
    'RECEIVED',
    'ACCEPTED'
);

CREATE TABLE PGC_OBJECT_TYPE (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    PARENT_TYPE                 INTEGER             REFERENCES PGC_OBJECT_TYPE (ID) ON DELETE CASCADE,
    AUTONUMBER_SOURCE           INTEGER             REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PGC_OBJECT_TYPE_ATTRIBUTE (
    ATTRIBUTE_ID                INTEGER             NOT NULL PRIMARY KEY,
    TYPE                        INTEGER             NOT NULL REFERENCES PGC_OBJECT_TYPE (ID) ON DELETE CASCADE,
    SEQ                         INTEGER             ,
    FOREIGN KEY (ATTRIBUTE_ID)  REFERENCES          OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);


CREATE TABLE PGC_OBJECT (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    NAME                        TEXT                    NOT NULL,
    NUMBER                      TEXT                    NOT NULL,
    DESCRIPTION                 TEXT                    ,
    FOREIGN KEY (ID)            REFERENCES              CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PGC_OBJECT_ATTRIBUTE (
    OBJECT                        INTEGER             NOT NULL REFERENCES PGC_OBJECT (ID) ON DELETE CASCADE,
    ATTRIBUTE                     INTEGER             NOT NULL REFERENCES PGC_OBJECT_TYPE_ATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (OBJECT, ATTRIBUTE)  REFERENCES       OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF)  ON DELETE CASCADE,
    UNIQUE (OBJECT, ATTRIBUTE)
);

CREATE TABLE PGC_OBJECT_FILE (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    OBJECT                      INTEGER             NOT NULL REFERENCES PGC_OBJECT (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PLM_FILE (FILE_ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SUBSTANCE_TYPE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT_TYPE (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SUBSTANCEGROUP_TYPE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT_TYPE (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_DECLARATION_TYPE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT_TYPE (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SPECIFICATION_TYPE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT_TYPE (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_MATERIAL (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SUBSTANCE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    TYPE                        INTEGER                 NOT NULL REFERENCES PGC_SUBSTANCE_TYPE(ID) ON DELETE CASCADE,
    CAS_NUMBER                  TEXT                    ,
    CA_NUMBER                   TEXT                    ,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SUBSTANCEGROUP (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    TYPE                        INTEGER                 NOT NULL REFERENCES PGC_SUBSTANCEGROUP_TYPE(ID) ON DELETE CASCADE,
    BASE_SUBSTANCE              INTEGER                 NOT NULL REFERENCES PGC_SUBSTANCE (ID) ON DELETE CASCADE,
    CONVERSION_FACTOR           DOUBLE PRECISION        NOT NULL DEFAULT 1.0,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SPECIFICATION (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    TYPE                        INTEGER                 NOT NULL REFERENCES PGC_SPECIFICATION_TYPE(ID) ON DELETE CASCADE,
    ACTIVE                      BOOLEAN                 NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_SPECIFICATION_SUBSTANCE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    SPECIFICATION               INTEGER                 NOT NULL REFERENCES PGC_SPECIFICATION(ID) ON DELETE CASCADE,
    SUBSTANCE                   INTEGER                 NOT NULL REFERENCES PGC_SUBSTANCE (ID) ON DELETE CASCADE,
    DATE_OF_INCLUSION           DATE                    ,
    REASON_FOR_INCLUSION        TEXT                    ,
    THRESHOLD_PPM               INTEGER                 NOT NULL DEFAULT 0,
    THRESHOLD_MASS DOUBLE PRECISION NOT NULL DEFAULT 0,
    UOM            INTEGER REFERENCES MEASUREMENT_UNIT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_ITEM_SPECIFICATION (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    ITEM                        INTEGER                 NOT NULL REFERENCES PLM_ITEMREVISION (ITEM_ID) ON DELETE CASCADE,
    SPECIFICATION               INTEGER                 NOT NULL REFERENCES PGC_SPECIFICATION (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_PART_SPECIFICATION (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    PART                        INTEGER                 NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    SPECIFICATION               INTEGER                 NOT NULL REFERENCES PGC_SPECIFICATION (ID) ON DELETE CASCADE,
    COMPLIANT                   BOOLEAN                 NOT NULL DEFAULT FALSE
);

CREATE TABLE PGC_DECLARATION (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    TYPE                        INTEGER                 NOT NULL REFERENCES PGC_DECLARATION_TYPE (ID) ON DELETE CASCADE,
    SUPPLIER                    INTEGER                 NOT NULL REFERENCES PLM_SUPPLIER (ID) ON DELETE CASCADE,
    CONTACT                     INTEGER                 NOT NULL REFERENCES PLM_SUPPLIER_CONTACT (ID) ON DELETE CASCADE,
    DUE_DATE                    DATE                    ,
    RECEIVED_DATE               TIMESTAMP               ,
    STATUS DECLARATION_STATUS DEFAULT 'OPEN',
    FOREIGN KEY (ID)            REFERENCES              PGC_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_DECLARATION_SPECIFICATION (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    DECLARATION                 INTEGER                 NOT NULL REFERENCES PGC_DECLARATION (ID) ON DELETE CASCADE,
    SPECIFICATION INTEGER NOT NULL REFERENCES PGC_SPECIFICATION (ID) ON DELETE CASCADE,
    UNIQUE (DECLARATION, SPECIFICATION)
);


CREATE TABLE PGC_BOS (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    PART                        INTEGER                 NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE
);

CREATE TABLE PGC_BOS_ITEM (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    BOS                         INTEGER                 NOT NULL REFERENCES PGC_BOS (ID) ON DELETE CASCADE,
    TYPE                        BOS_ITEM_TYPE           NOT NULL DEFAULT 'SUBSTANCE',
    MATERIAL                    INTEGER                 REFERENCES PGC_MATERIAL (ID) ON DELETE CASCADE,
    SUBSTANCE                   INTEGER                 REFERENCES PGC_SUBSTANCE (ID) ON DELETE CASCADE,
    SUBSTANCE_GROUP             INTEGER                 REFERENCES PGC_SUBSTANCEGROUP (ID) ON DELETE CASCADE,
    QUANTITY                    INTEGER                 ,
    MASS                        DOUBLE PRECISION        ,
    UOM                         INTEGER                 REFERENCES MEASUREMENT_UNIT (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_DECLARATION_PART (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    DECLARATION                 INTEGER                 NOT NULL REFERENCES PGC_DECLARATION (ID) ON DELETE CASCADE,
    PART                        INTEGER                 NOT NULL REFERENCES PLM_MANUFACTURERPART (MFRPART_ID) ON DELETE CASCADE,
    BOS                         INTEGER                 REFERENCES PGC_BOS (ID) ON DELETE CASCADE
);

CREATE TABLE PGC_DECLARATION_PART_COMPLIANCE (
    ID                          INTEGER                 NOT NULL PRIMARY KEY,
    DECLARATION_PART            INTEGER                 NOT NULL REFERENCES PGC_DECLARATION_PART (ID) ON DELETE CASCADE,
    DECLARATION_SPEC            INTEGER                 NOT NULL REFERENCES PGC_DECLARATION_SPECIFICATION (ID) ON DELETE CASCADE,
    COMPLIANT                   BOOLEAN                 NOT NULL DEFAULT FALSE,
    UNIQUE (DECLARATION_PART, DECLARATION_SPEC)
);
