CREATE SEQUENCE PDM_OBJECT_ID_SEQ START 1 INCREMENT 1;

CREATE TYPE PDM_OBJECT_TYPE AS ENUM (
    'PDM_ASSEMBLY',
    'PDM_PART',
    'PDM_DRAWING',
    'PDM_DRAWINGTEMPLATE',
    'PDM_CONFIGURATION',
    'PDM_BOMOCCURRENCE',
    'PDM_FILE',
    'PDM_FILEVERSION',
    'PDM_FOLDER',
    'PDM_VAULT',
    'PDM_COMMIT'
);

CREATE TYPE PDM_ATTRIBUTE_DATATYPE AS ENUM (
    'TEXT',
    'INTEGER',
    'DOUBLE',
    'BOOLEAN',
    'DATE'
);

CREATE TYPE PDM_FILE_TYPE AS ENUM (
    'ASSEMBLY',
    'PART',
    'DRAWING',
    'NORMAL'
);

CREATE TABLE PDM_OBJECT (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    NAME                        TEXT                NOT NULL,
    DESCRIPTION                 TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PDM_OBJECT_ATTRIBUTE (
    ID                          INTEGER             NOT NULL PRIMARY KEY DEFAULT nextval('PDM_OBJECT_ID_SEQ'),
    OBJECT                      INTEGER             NOT NULL REFERENCES PDM_OBJECT (ID) ON DELETE CASCADE,
    NAME                        TEXT                NOT NULL,
    DATATYPE                    PDM_ATTRIBUTE_DATATYPE NOT NULL DEFAULT 'TEXT',
    TEXT_VALUE                  TEXT                ,
    INTEGER_VALUE               INTEGER             ,
    DOUBLE_VALUE                DOUBLE PRECISION    ,
    BOOLEAN_VALUE               BOOLEAN             ,
    DATE_VALUE                  DATE
);

CREATE TABLE PDM_VAULT (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)            REFERENCES          PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_COMMIT (
    ID                        INTEGER                PRIMARY KEY,
    VAULT                     INTEGER                NOT NULL REFERENCES PDM_VAULT (ID) ON DELETE CASCADE,
    HASH                      TEXT                   ,
    MESSAGE                   TEXT                   NOT NULL,
    UNIQUE (HASH),
    FOREIGN KEY (ID)          REFERENCES             PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_VAULT_OBJECT (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    VAULT                       INTEGER             NOT NULL REFERENCES PDM_VAULT (ID) ON DELETE CASCADE,
    NAMEPATH                    TEXT                ,
    IDPATH                      TEXT                ,
    CHECKED_OUT                 BOOLEAN             NOT NULL DEFAULT FALSE,
    CHECKED_OUT_BY              INTEGER             REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    CHECKED_OUT_TIMESTAMP       TIMESTAMP           ,
    CHECKED_OUT_IPADDRESS       TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_FOLDER (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    PARENT                      INTEGER             REFERENCES PDM_FOLDER (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)            REFERENCES          PDM_VAULT_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_FILE (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    FOLDER                      INTEGER             REFERENCES PDM_FOLDER (ID)  ON DELETE CASCADE,
    LATEST_VERSION              INTEGER             DEFAULT 1,
    VERSIONS                    INTEGER             DEFAULT 1,
    FILE_TYPE                   PDM_FILE_TYPE       NOT NULL DEFAULT 'NORMAL',
    AUTHORING_APP               TEXT                ,
    AUTHORING_APP_VERSION       TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          PDM_VAULT_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_FILE_VERSION (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    FILE                        INTEGER             REFERENCES PDM_FILE (ID)  ON DELETE CASCADE,
    COMMIT                      INTEGER             NOT NULL REFERENCES PDM_COMMIT (ID) ON DELETE CASCADE,
    VERSION                     INTEGER             NOT NULL,
    LATEST                      BOOLEAN             NOT NULL DEFAULT TRUE,
    SIZE                        BIGINT              NOT NULL,
    TIMESTAMP                   BIGINT              ,
    ATTACHED_TO                 INTEGER             REFERENCES PDM_OBJECT (ID) ON DELETE CASCADE,
    VISUALIZATION_ID            TEXT                ,
    PART_REFERENCES             TEXT                ,
    FOREIGN KEY (ID)            REFERENCES          PDM_VAULT_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_OBJECT_FILE (
    ID                      INTEGER                 NOT NULL PRIMARY KEY DEFAULT nextval('OBJECT_ID_SEQ'),
    OBJECT                  INTEGER                 NOT NULL REFERENCES PDM_OBJECT (ID) ON DELETE CASCADE,
    FILE                    INTEGER                 NOT NULL REFERENCES PDM_FILE (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_MASTER_OBJECT (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    LATEST_REVISION         TEXT                    NOT NULL,
    LATEST_VERSION          INTEGER                 NOT NULL,
    FOREIGN KEY (ID)        REFERENCES              PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_REVISIONED_OBJECT (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    MASTER                  INTEGER                 NOT NULL REFERENCES PDM_MASTER_OBJECT (ID) ON DELETE CASCADE,
    REVISION                TEXT                    NOT NULL,
    LATEST_REVISION         BOOLEAN                 NOT NULL DEFAULT TRUE,
    VERSION                 INTEGER                 NOT NULL,
    LATEST_VERSION          BOOLEAN                 NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID)        REFERENCES              PDM_VAULT_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_OBJECT_THUMBNAIL (
    ID                      INTEGER                 NOT NULL PRIMARY KEY REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    THUMBNAIL               BYTEA
);

CREATE TABLE PDM_ASSEMBLY (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)        REFERENCES              PDM_REVISIONED_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_PART (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    STANDARD_PART           BOOLEAN                 NOT NULL DEFAULT FALSE,
    FOREIGN KEY (ID)        REFERENCES              PDM_REVISIONED_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_DRAWING (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    ATTACHED_TO             INTEGER                 REFERENCES PDM_REVISIONED_OBJECT (ID) ON DELETE CASCADE,
    PDF_FILE                INTEGER                 REFERENCES ATTACHMENT(ATTACHMENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (ID)        REFERENCES              PDM_REVISIONED_OBJECT (ID) ON DELETE CASCADE
);

ALTER TABLE PDM_ASSEMBLY ADD COLUMN DRAWING_MASTER INTEGER REFERENCES PDM_MASTER_OBJECT (ID) ON DELETE SET NULL;
ALTER TABLE PDM_ASSEMBLY ADD COLUMN DRAWING INTEGER REFERENCES PDM_DRAWING (ID) ON DELETE SET NULL;
ALTER TABLE PDM_PART ADD COLUMN DRAWING_MASTER INTEGER REFERENCES PDM_MASTER_OBJECT (ID) ON DELETE SET NULL;
ALTER TABLE PDM_PART ADD COLUMN DRAWING INTEGER REFERENCES PDM_DRAWING (ID) ON DELETE SET NULL;


CREATE TABLE PDM_CONFIGURATION (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID)        REFERENCES              PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_ASSEMBLY_CONFIGURATION (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    ASSEMBLY                INTEGER                 NOT NULL REFERENCES PDM_ASSEMBLY (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_CONFIGURATION (ID) ON DELETE CASCADE
);

ALTER TABLE PDM_ASSEMBLY ADD COLUMN DEFAULT_CONFIGURATION INTEGER REFERENCES PDM_ASSEMBLY_CONFIGURATION (ID) ON DELETE CASCADE;

CREATE TABLE PDM_PART_CONFIGURATION (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    PART                    INTEGER                 NOT NULL REFERENCES PDM_PART (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_CONFIGURATION (ID) ON DELETE CASCADE
);

ALTER TABLE PDM_PART ADD COLUMN DEFAULT_CONFIGURATION INTEGER REFERENCES PDM_PART_CONFIGURATION (ID) ON DELETE CASCADE;

CREATE TABLE PDM_DRAWING_CONFIGURATION (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    DRAWING                 INTEGER                 NOT NULL REFERENCES PDM_DRAWING (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_CONFIGURATION (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_BOM_OCCURRENCE (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    PARENT                  INTEGER                 NOT NULL REFERENCES PDM_ASSEMBLY_CONFIGURATION (ID) ON DELETE CASCADE,
    QUANTITY                INTEGER                 NOT NULL,
    NOTES                   TEXT                    ,
    FOREIGN KEY (ID)        REFERENCES              PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_ASSEMBLY_BOM_OCCURRENCE (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    ASSEMBLY                INTEGER                 NOT NULL REFERENCES PDM_ASSEMBLY_CONFIGURATION (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_BOM_OCCURRENCE (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_PART_BOM_OCCURRENCE (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    PART                    INTEGER                 NOT NULL REFERENCES PDM_PART_CONFIGURATION (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_BOM_OCCURRENCE (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_DRAWING_TEMPLATE (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    TEMPLATE_FILE           INTEGER                 REFERENCES ATTACHMENT (ATTACHMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_OBJECT (ID) ON DELETE CASCADE
);

/* Link PDM and PLM Objects */
ALTER TABLE PLM_ITEM ADD COLUMN DESIGN_OBJECT INTEGER REFERENCES PDM_MASTER_OBJECT (ID) ON DELETE SET NULL;
ALTER TABLE PLM_ITEMREVISION ADD COLUMN DESIGN_OBJECT INTEGER REFERENCES PDM_REVISIONED_OBJECT (ID) ON DELETE SET NULL;

ALTER TABLE PDM_MASTER_OBJECT ADD COLUMN ITEM_OBJECT INTEGER REFERENCES PLM_ITEM (ITEM_ID) ON DELETE SET NULL;
ALTER TABLE PDM_REVISIONED_OBJECT ADD COLUMN ITEM_OBJECT INTEGER REFERENCES PLM_ITEMREVISION (ITEM_ID) ON DELETE SET NULL;


/* GitHub Tables */
CREATE TYPE GITHUB_AUTH_TYPE AS ENUM (
    'PASSWORD',
    'TOKEN'
);

CREATE TABLE PDM_GITHUB_ACCOUNT (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    AUTH_TYPE               GITHUB_AUTH_TYPE        NOT NULL DEFAULT 'TOKEN',
    USERNAME                TEXT                    ,
    PASSWORD                TEXT                    ,
    OAUTH_TOKEN             TEXT                    ,
    ORGANIZATION            TEXT                    NOT NULL,
    FOREIGN KEY (ID)        REFERENCES              PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_GITHUB_REPOSITORY (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    ACCOUNT                 INTEGER                 NOT NULL REFERENCES PDM_GITHUB_ACCOUNT (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              PDM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_GITHUB_ITEM_REPOSITORY (
    ITEM                    INTEGER                 NOT NULL PRIMARY KEY REFERENCES PLM_ITEM (ITEM_ID) ON DELETE CASCADE,
    REPOSITORY              INTEGER                 NOT NULL REFERENCES PDM_GITHUB_REPOSITORY (ID) ON DELETE CASCADE
);

CREATE TABLE PDM_GITHUB_ITEMREVISION_RELEASE (
    ITEM_REVISION           INTEGER                 NOT NULL PRIMARY KEY REFERENCES PLM_ITEMREVISION (ITEM_ID) ON DELETE CASCADE,
    RELEASE_ID              BIGINT                  NOT NULL,
    RELEASE_NAME            TEXT                    NOT NULL,
    COMMENTS                TEXT                    NOT NULL,
    RELEASE_DATE            TIMESTAMP               NOT NULL
);

CREATE TABLE PDM_GITHUB_ITEMREVISION_RELEASE_ASSET (
    ID                      INTEGER                 NOT NULL PRIMARY KEY,
    RELEASE                 INTEGER                 NOT NULL REFERENCES PDM_GITHUB_ITEMREVISION_RELEASE (ITEM_REVISION) ON DELETE CASCADE,
    FOREIGN KEY (ID)        REFERENCES              ATTACHMENT (ATTACHMENT_ID) ON DELETE CASCADE
);
