/* Begin common tables */
-- noinspection SqlNoDataSourceInspection
CREATE TABLE COUNTRY (
  COUNTRY_ID INTEGER      NOT NULL PRIMARY KEY,
  NAME       VARCHAR(100) NOT NULL UNIQUE,
  SHORT_NAME VARCHAR(10),
  FOREIGN KEY (COUNTRY_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE STATE (
  STATE_ID   INTEGER      NOT NULL PRIMARY KEY,
  COUNTRY    INTEGER      NOT NULL REFERENCES COUNTRY (COUNTRY_ID) ON DELETE CASCADE,
  NAME       VARCHAR(100) NOT NULL UNIQUE,
  SHORT_NAME VARCHAR(10),
  FOREIGN KEY (STATE_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE DISTRICT (
  DISTRICT_ID INTEGER      NOT NULL PRIMARY KEY,
  STATE       INTEGER      NOT NULL REFERENCES STATE (STATE_ID) ON DELETE CASCADE,
  NAME        VARCHAR(100) NOT NULL UNIQUE,
  FOREIGN KEY (DISTRICT_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);


CREATE TABLE ADDRESSTYPE (
  TYPE_ID     INTEGER NOT NULL PRIMARY KEY,
  NAME        TEXT    NOT NULL UNIQUE,
  DESCRIPTION TEXT
);

CREATE TABLE ADDRESS (
  ADDRESS_ID   INTEGER NOT NULL PRIMARY KEY,
  ADDRESS_TYPE INTEGER NOT NULL REFERENCES ADDRESSTYPE (TYPE_ID) ON DELETE CASCADE,
  ADDRESS_TEXT TEXT    NOT NULL,
  CITY         VARCHAR(100),
  DISTRICT     VARCHAR(100),
  STATE        INTEGER NOT NULL REFERENCES STATE (STATE_ID) ON DELETE CASCADE,
  COUNTRY      INTEGER NOT NULL REFERENCES COUNTRY (COUNTRY_ID) ON DELETE CASCADE,
  PINCODE      VARCHAR(20),
  FOREIGN KEY (ADDRESS_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PERSONTYPE (
  TYPE_ID     INTEGER NOT NULL PRIMARY KEY,
  NAME        TEXT    NOT NULL UNIQUE,
  DESCRIPTION TEXT
);

CREATE TABLE MOBILEDEVICE (
  DEVICE_ID                TEXT NOT NULL PRIMARY KEY,
  SENDER_ID                TEXT NOT NULL,
  OS                       TEXT,
  OS_VERSION               TEXT,
  MANUFACTURER             TEXT,
  DEVICE_INFO              TEXT,
  DISABLE_PUSHNOTIFICATION BOOLEAN DEFAULT FALSE
);

CREATE TABLE PROFILE (
  PROFILE_ID      INTEGER       NOT NULL PRIMARY KEY,
  NAME            TEXT          NOT NULL,
  PROFILE_DATA    TEXT[]        ,
  DEFAULT_PROFILE BOOLEAN       NOT NULL DEFAULT FALSE,
  FOREIGN KEY (PROFILE_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE PERSONGROUP (
  GROUP_ID    INTEGER NOT NULL PRIMARY KEY,
  NAME        TEXT    NOT NULL,
  DESCRIPTION TEXT,
  IS_ACTIVE   BOOLEAN,
  EXTERNAL    BOOLEAN,
  PROFILE     INTEGER             REFERENCES PROFILE (PROFILE_ID) ON DELETE CASCADE,
  PARENT      INTEGER
);

CREATE TABLE PERSON (
  PERSON_ID       INTEGER NOT NULL PRIMARY KEY,
  PERSON_TYPE     INTEGER NOT NULL REFERENCES PERSONTYPE (TYPE_ID) ON DELETE CASCADE,
  TITLE           VARCHAR(10),
  FIRST_NAME      VARCHAR(32),
  LAST_NAME       VARCHAR(32),
  MIDDLE_NAME     VARCHAR(32),
  PHONE_OFFICE    VARCHAR(100),
  PHONE_MOBILE    VARCHAR(100),
  EMAIL           VARCHAR(100),
  IMAGE           BYTEA,
  EMAIL_VERIFIED  BOOLEAN DEFAULT FALSE,
  MOBILE_DEVICE TEXT REFERENCES MOBILEDEVICE (DEVICE_ID) ON DELETE SET NULL,
  DEFAULT_GROUP INTEGER REFERENCES PERSONGROUP (GROUP_ID) ON DELETE CASCADE,
  FOREIGN KEY (PERSON_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE GROUPMEMBER (
  ROWID    INTEGER NOT NULL PRIMARY KEY,
  GROUP_ID INTEGER NOT NULL REFERENCES PERSONGROUP (GROUP_ID) ON DELETE CASCADE,
  PERSON   INTEGER NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
  UNIQUE (GROUP_ID, PERSON)
);

CREATE TABLE PERSONADDRESS (
  PERSON_ID  INTEGER NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
  ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS (ADDRESS_ID) ON DELETE CASCADE,
  UNIQUE (PERSON_ID, ADDRESS_ID)
);

CREATE TABLE TAG (
  TAG_ID      INTEGER     NOT NULL PRIMARY KEY,
  LABEL       TEXT        NOT NULL,
  OBJECT_TYPE OBJECT_TYPE NOT NULL,
  OBJECT   INTEGER     NOT NULL REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE LOCATIONAWAREOBJECT (
  OBJECT_ID INTEGER NOT NULL PRIMARY KEY,
  FOREIGN KEY (OBJECT_ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE OBJECTGEOLOCATION (
  OBJECT_ID   INTEGER          NOT NULL PRIMARY KEY REFERENCES LOCATIONAWAREOBJECT (OBJECT_ID) ON DELETE CASCADE,
  OBJECT_TYPE OBJECT_TYPE      NOT NULL,
  LATITUDE    DOUBLE PRECISION NOT NULL,
  LONGITUDE   DOUBLE PRECISION NOT NULL,
  UNIQUE (OBJECT_ID, OBJECT_TYPE)
);

CREATE TABLE PREFERENCE (
  ID                  INTEGER NOT NULL PRIMARY KEY,
  CONTEXT             TEXT    NOT NULL,
  PREFERENCE_KEY      TEXT    NOT NULL,
  STRING_VALUE        TEXT,
  INTEGER_VALUE       INTEGER,
  DECIMAL_VALUE       DOUBLE PRECISION,
  DATE_VALUE          DATE,
  TIME_VALUE          TIME,
  DATETIME_VALUE      TIMESTAMP,
  BOOLEAN_VALUE       BOOLEAN,
  STRING_ARRAY_VALUE  TEXT [],
  INTEGER_ARRAY_VALUE INTEGER [],
  CUSTOM_LOGO         BYTEA,
  JSON_VALUE          TEXT
);

CREATE TABLE SYSTEM_PREFERENCE (
  ID INTEGER NOT NULL PRIMARY KEY,
  FOREIGN KEY (ID) REFERENCES PREFERENCE (ID) ON DELETE CASCADE
);

CREATE TABLE USER_PREFERENCE (
  ID                INTEGER   NOT NULL PRIMARY KEY,
  USER_THEME        TEXT,
  PREFERRED_PAGE    TEXT,
  USER_DATE_FORMAT  TEXT      DEFAULT NULL,
  SHORT_DATE_FORMAT TEXT      DEFAULT NULL,
  USER_WIDGET_JSON  TEXT,
  SWITCH_ROLE       BOOLEAN   DEFAULT FALSE
);

CREATE TABLE ENABLED_PLUGIN (
    ID TEXT NOT NULL PRIMARY KEY
);


/* Activity Stream tables */

CREATE TABLE ACTIVITY_STREAM_OBJECT (
    ID              BIGINT       NOT NULL PRIMARY KEY DEFAULT nextval('ACTIVITYSTREAM_ID_SEQ'),
    OBJECT          INTEGER      NOT NULL,
    TYPE            TEXT         NOT NULL
);

CREATE TABLE ACTIVITY_STREAM (
    ID              BIGINT      NOT NULL PRIMARY KEY DEFAULT nextval('ACTIVITYSTREAM_ID_SEQ'),
    ACTIVITY        TEXT        NOT NULL,
    ACTOR           BIGINT      NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    OBJECT          BIGINT      NOT NULL REFERENCES ACTIVITY_STREAM_OBJECT (ID) ON DELETE CASCADE,
    SOURCE          BIGINT      REFERENCES ACTIVITY_STREAM_OBJECT (ID) ON DELETE CASCADE,
    TARGET          BIGINT      REFERENCES ACTIVITY_STREAM_OBJECT (ID) ON DELETE CASCADE,
    CONTEXT         BIGINT      REFERENCES ACTIVITY_STREAM_OBJECT (ID) ON DELETE CASCADE,
    TIMESTAMP       TIMESTAMP   NOT NULL,
    RESULT          TEXT        ,
    CONVERTER       TEXT        NOT NULL,
    DATA            TEXT
    /* SESSION column will be added later */
);

CREATE TABLE APP_NAVIGATION (
  MENU_ID                 TEXT                NOT NULL PRIMARY KEY,
  NAME                    TEXT                NOT NULL,
  UNIQUE (MENU_ID, NAME)
);

CREATE TABLE GROUP_PROFILE (
  ID                      INTEGER             NOT NULL PRIMARY KEY,
  PERSON_GROUP            INTEGER             NOT NULL REFERENCES PERSONGROUP (GROUP_ID) ON DELETE CASCADE,
  PROFILE                 INTEGER             NOT NULL REFERENCES PROFILE (PROFILE_ID) ON DELETE CASCADE,
  UNIQUE (PERSON_GROUP, PROFILE)
);

/* End common tables */
