CREATE TYPE WORKFLOW_STATUS AS ENUM (
  'PENDING',
  'STARTED',
  'FINISHED'
);

CREATE TYPE ACTIVITY_STATUS AS ENUM (
  'PENDING',
  'STARTED',
  'FINISHED'
);

CREATE TYPE WORKFLOW_TASK_STATUS AS ENUM (
  'PENDING',
  'FINISHED'
);

CREATE TYPE ACTIVITY_TYPE AS ENUM (
  'START',
  'END',
  'NORMAL'
);

CREATE TABLE WORKFLOWDEFINITION (
  ID            INTEGER NOT NULL PRIMARY KEY,
  NAME          TEXT    NOT NULL,
  DESCRIPTION   TEXT,
  DIAGRAM       TEXT,
  DIAGRAM_ID    TEXT,
  ASSIGNABLE_TO TEXT [],
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE WORKFLOW (
  ID                   INTEGER         NOT NULL PRIMARY KEY,
  NAME                 TEXT            NOT NULL,
  DESCRIPTION          TEXT,
  DEFINITION           INTEGER         NOT NULL REFERENCES WORKFLOWDEFINITION (ID) ON DELETE SET NULL,
  DIAGRAM              TEXT,
  DIAGRAM_ID           TEXT,
  ATTACHED_OBJECT_TYPE OBJECT_TYPE     NOT NULL,
  ATTACHED_OBJECT_ID   INTEGER         NOT NULL REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
  STATUS               WORKFLOW_STATUS NOT NULL DEFAULT 'PENDING',
  START_DATE           TIMESTAMP,
  FINISH_DATE          TIMESTAMP,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE ACTIVITYDEFINITION (
  ID          INTEGER       NOT NULL PRIMARY KEY,
  WORKFLOW    INTEGER       NOT NULL REFERENCES WORKFLOWDEFINITION (ID) ON DELETE CASCADE,
  NAME        TEXT          NOT NULL,
  DESCRIPTION TEXT,
  TYPE        ACTIVITY_TYPE NOT NULL,
  DIAGRAM_ID  TEXT/*,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE*/
);

CREATE TABLE ACTIVITY (
  ID          INTEGER         NOT NULL PRIMARY KEY,
  NAME        TEXT            NOT NULL,
  DESCRIPTION TEXT,
  TYPE        ACTIVITY_TYPE   NOT NULL,
  DIAGRAM_ID  TEXT,
  WORKFLOW    INTEGER         NOT NULL REFERENCES WORKFLOW (ID) ON DELETE CASCADE,
  /* SELECTED_ACTION column added after ACTION table is create. See below. */
  STATUS      ACTIVITY_STATUS NOT NULL DEFAULT 'PENDING',
  START_DATE  TIMESTAMP,
  FINISH_DATE TIMESTAMP/*,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE*/
);

CREATE TABLE ACTIVITYASSIGNMENT (
  ROWID       INTEGER    NOT NULL PRIMARY KEY ,
  ACTIVITY    INTEGER    NOT NULL REFERENCES ACTIVITY(ID)ON DELETE CASCADE ,
  ASSIGNEDTO  INTEGER    NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE
);

ALTER TABLE WORKFLOW ADD COLUMN CURRENT_ACTIVITY INTEGER REFERENCES ACTIVITY (ID) ON DELETE CASCADE;

CREATE TABLE ACTIONDEFINITION (
  ID         INTEGER NOT NULL PRIMARY KEY,
  NAME       TEXT    NOT NULL,
  SOURCE     INTEGER NOT NULL REFERENCES ACTIVITYDEFINITION (ID) ON DELETE CASCADE,
  TARGET     INTEGER NOT NULL REFERENCES ACTIVITYDEFINITION (ID) ON DELETE CASCADE,
  DIAGRAM_ID TEXT,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE ACTION (
  ID         INTEGER NOT NULL PRIMARY KEY,
  NAME       TEXT    NOT NULL,
  DIAGRAM_ID TEXT,
  SOURCE     INTEGER NOT NULL REFERENCES ACTIVITY (ID) ON DELETE CASCADE,
  TARGET     INTEGER NOT NULL REFERENCES ACTIVITY (ID) ON DELETE CASCADE,
  ACTOR      INTEGER REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
  TIMESTAMP  TIMESTAMP,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

ALTER TABLE ACTIVITY ADD COLUMN SELECTED_ACTION INTEGER REFERENCES ACTION (ID) ON DELETE CASCADE;

CREATE TABLE TASKDEFINITION (
  ID          INTEGER NOT NULL PRIMARY KEY,
  NAME        TEXT    NOT NULL,
  DESCRIPTION TEXT,
  ACTIVITY    INTEGER NOT NULL REFERENCES ACTIVITYDEFINITION (ID) ON DELETE CASCADE,
  OPTIONAL    BOOLEAN NOT NULL DEFAULT FALSE,
  NOTES       TEXT,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE ACTIVITYTASK (
  ID          INTEGER              NOT NULL PRIMARY KEY,
  ACTIVITY    INTEGER              NOT NULL REFERENCES ACTIVITY (ID) ON DELETE CASCADE,
  NAME        TEXT                 NOT NULL,
  DESCRIPTION TEXT,
  OPTIONAL    BOOLEAN              NOT NULL DEFAULT FALSE,
  STATUS      WORKFLOW_TASK_STATUS NOT NULL DEFAULT 'PENDING',
  FINISH_DATE TIMESTAMP,
  NOTES       TEXT,
  FOREIGN KEY (ID) REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE WORKFLOWHISTORY (
  ROWID         INTEGER NOT NULL PRIMARY KEY,
  WORKFLOW      INTEGER NOT NULL REFERENCES WORKFLOW (ID) ON DELETE CASCADE,
  FROM_ACTIVITY INTEGER REFERENCES ACTIVITY (ID) ON DELETE CASCADE,
  ACTION        INTEGER REFERENCES ACTION (ID) ON DELETE CASCADE,
  TO_ACTIVTY    INTEGER REFERENCES ACTIVITY (ID) ON DELETE CASCADE,
  TIMESTAMP     TIMESTAMP DEFAULT NOW(),
  PERSON        INTEGER REFERENCES PERSON (PERSON_ID) ON DELETE SET NULL
);

CREATE TABLE WORKFLOWUSERINBOX (
  WFMINBOX_ID INTEGER NOT NULL PRIMARY KEY,
  WORKFLOW_ID INTEGER NOT NULL REFERENCES WORKFLOW (ID) ON DELETE CASCADE,
  FOREIGN KEY (WFMINBOX_ID) REFERENCES USERINBOX (INBOX_ID) ON DELETE CASCADE
);


/*
CREATE TABLE WORKFLOWEVENT (
    ID                  INTEGER                 NOT NULL PRIMARY KEY,
    OBJECT_TYPE         OBJECT_TYPE             NOT NULL,
    OBJECT_ID           INTEGER                 NOT NULL REFERENCES CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE,
    EVENT               WORKFLOW_EVENT          NOT NULL
);

CREATE TABLE WORKFLOWEVENTACTION (
    ID                  INTEGER                 NOT NULL PRIMARY KEY,
    ACTION              WORKFLOW_ACTION         NOT NULL,
    EVENT               INTEGER                 NOT NULL REFERENCES WORKFLOWEVENT (ID) ON DELETE CASCADE
);
*/
