/* Custom types and objects */
CREATE SEQUENCE CUSTOM_ID_SEQ           START 1 INCREMENT 1;

CREATE TABLE CUSTOM_OBJECT_TYPE (
    ID                  INTEGER         PRIMARY KEY  NOT NULL,
    NAME                TEXT            NOT NULL,
    DESCRIPTION         TEXT            NOT NULL,
    ABSTRACT            BOOLEAN         NOT NULL DEFAULT FALSE,
    PARENT              INTEGER         REFERENCES CUSTOM_OBJECT_TYPE(ID) ON DELETE CASCADE,
    NUMBER_SOURCE       INTEGER         REFERENCES AUTONUMBER (AUTONUMBER_ID) ON DELETE CASCADE,
    IS_REVISIONED       BOOLEAN         NOT NULL DEFAULT FALSE,
    REVISION_SEQUENCE   INTEGER         REFERENCES LOV (LOV_ID) ON DELETE CASCADE,
    HAS_LIFECYCLE       BOOLEAN         NOT NULL DEFAULT FALSE,
    SHOW_IN_NAVIGATION  BOOLEAN         NOT NULL DEFAULT TRUE,
    LIFECYCLE           INTEGER         REFERENCES LOV (LOV_ID) ON DELETE CASCADE,
    TABS                TEXT[]
);

CREATE TABLE CUSTOM_OBJECT_TYPE_ATTRIBUTE (
    ID                  INTEGER         PRIMARY KEY  NOT NULL,
    SEQ_NO              INTEGER         NOT NULL,
    CUSTOM_OBJECT_TYPE  INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT_TYPE(ID) ON DELETE CASCADE,
    REVISION_SPECIFIC   BOOLEAN         NOT NULL DEFAULT FALSE,
    SHOW_IN_TABLE       BOOLEAN         NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID)    REFERENCES      OBJECTTYPEATTRIBUTE (ATTRIBUTE_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_OBJECT (
    ID                  INTEGER         PRIMARY KEY  NOT NULL,
    TYPE                INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT_TYPE(ID) ON DELETE CASCADE,
    NUMBER              TEXT            NOT NULL,
    NAME                TEXT            NOT NULL,
    DESCRIPTION         TEXT            NOT NULL,
--     SUPPLIER            INTEGER         REFERENCES PLM_SUPPLIER(ID) ON DELETE CASCADE,
    UNIQUE (NUMBER),
    FOREIGN KEY (ID)    REFERENCES      CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_OBJECT_WITH_LIFECYCLE (
    ID                  INTEGER         PRIMARY KEY  NOT NULL,
    LIFECYCLE           TEXT            NOT NULL,
    FOREIGN KEY (ID)    REFERENCES      CUSTOM_OBJECT (ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_REVISIONED_OBJECT (
    ID                  INTEGER         PRIMARY KEY  NOT NULL,
    REVISION            TEXT            NOT NULL,
    LATEST              BOOLEAN         NOT NULL DEFAULT TRUE,
    RELEASED_DATE       TIMESTAMP,
    FOREIGN KEY (ID)    REFERENCES      CUSTOM_OBJECT_WITH_LIFECYCLE (ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_OBJECT_LIFECYCLE_HISTORY (
    ID                  INTEGER         NOT NULL PRIMARY KEY,
    OBJECT              INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT_WITH_LIFECYCLE (ID) ON DELETE CASCADE,
    OLD_STATUS          TEXT            NOT NULL,
    NEW_STATUS          TEXT            NOT NULL,
    TIMESTAMP           TIMESTAMP       NOT NULL,
    UPDATED_BY          INTEGER         NOT NULL REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_REVISIONED_OBJECT_LIFECYCLE_HISTORY (
    ID                  INTEGER         NOT NULL PRIMARY KEY,
    OBJECT              INTEGER         NOT NULL REFERENCES CUSTOM_REVISIONED_OBJECT (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)    REFERENCES      CUSTOM_OBJECT_LIFECYCLE_HISTORY (ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_OBJECT_ATTRIBUTE (
    OBJECT_ID           INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT(ID) ON DELETE CASCADE,
    ATTRIBUTE_ID        INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT_TYPE_ATTRIBUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (OBJECT_ID, ATTRIBUTE_ID)   REFERENCES OBJECTATTRIBUTE (OBJECT_ID, ATTRIBUTEDEF) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_FILE (
    ID                 INTEGER          NOT NULL PRIMARY KEY,
    NUMBER             TEXT             NOT NULL ,
    NAME               TEXT             NOT NULL,
    DESCRIPTION        TEXT             ,
    SIZE               BIGINT           NOT NULL,
    VERSION            INTEGER          NOT NULL DEFAULT 1,
    LATEST             BOOLEAN          NOT NULL DEFAULT TRUE,
    LOCKED             BOOLEAN          NOT NULL DEFAULT FALSE,
    LOCKED_BY          INTEGER          REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    LOCKED_DATE        TIMESTAMP        ,
    REPLACEFILENAME    TEXT             ,
    FILE_URN           TEXT             ,
    THUMBNAIL          TEXT             ,
    PARENT_FILE        INTEGER          REFERENCES CUSTOM_FILE(ID) ON DELETE CASCADE,
    FILE_TYPE          TEXT             NOT NULL DEFAULT 'FILE'
);

CREATE TABLE CUSTOM_OBJECT_FILE (
    ID                 INTEGER          NOT NULL PRIMARY KEY,
    OBJECT             INTEGER          NOT NULL REFERENCES CUSTOM_OBJECT (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)   REFERENCES       CUSTOM_FILE (ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_REVISIONED_OBJECT_FILE (
    ID                 INTEGER          NOT NULL PRIMARY KEY,
    OBJECT             INTEGER          NOT NULL REFERENCES CUSTOM_REVISIONED_OBJECT (ID) ON DELETE CASCADE,
    FOREIGN KEY (ID)   REFERENCES       CUSTOM_FILE (ID) ON DELETE CASCADE
);


CREATE TABLE CUSTOM_OBJECT_BOM (
    ID                  INTEGER         NOT NULL PRIMARY KEY,
    SEQUENCE            INTEGER         ,
    PARENT              INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT (ID) ON DELETE CASCADE,
    CHILD               INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT (ID) ON DELETE CASCADE,
    QUANTITY            INTEGER         NOT NULL DEFAULT 1,
    NOTES               TEXT            ,
    FOREIGN KEY (ID)    REFERENCES      CASSINI_OBJECT (OBJECT_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_OBJECT_RELATED (
   ID                  INTEGER         NOT NULL PRIMARY KEY,
   SEQUENCE            INTEGER         ,
   PARENT              INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT (ID) ON DELETE CASCADE,
   RELATED             INTEGER         NOT NULL REFERENCES CUSTOM_OBJECT (ID) ON DELETE CASCADE,
   NOTES               TEXT
);


CREATE TABLE CUSTOM_OBJECT_VIEW_GROUP (
    ID                 INTEGER          NOT NULL PRIMARY KEY,
    NAME               TEXT             NOT NULL,
    DESCRIPTION        TEXT             NOT NULL,
    ICON               TEXT             ,
    PERMISSIONS        TEXT
);

CREATE TABLE CUSTOM_OBJECT_VIEW (
    ID                 INTEGER          NOT NULL PRIMARY KEY,
    VIEW_GROUP         INTEGER          REFERENCES CUSTOM_OBJECT_VIEW_GROUP(ID) ON DELETE CASCADE,
    NAME               TEXT             NOT NULL,
    DESCRIPTION        TEXT             NOT NULL,
    OBJECT_TYPE        INTEGER          NOT NULL REFERENCES CUSTOM_OBJECT_TYPE(ID) ON DELETE CASCADE,
    ICON               TEXT             ,
    PERMISSIONS        TEXT
);
CREATE TABLE CUSTOM_FILE_DOWNLOAD_HISTORY (
    ID                          INTEGER             NOT NULL PRIMARY KEY,
    FILE_ID                     INTEGER             NOT NULL REFERENCES CUSTOM_FILE(ID) ON DELETE CASCADE,
    PERSON                      INTEGER             NOT NULL REFERENCES PERSON(PERSON_ID) ON DELETE CASCADE,
    DOWNLOAD_DATE               TIMESTAMP
);
