/* Begin enums */
CREATE TYPE OBJECT_TYPE AS ENUM (
    'CUSTOMER',
    'COUNTRY',
    'STATE',
    'DISTRICT',
    'ADDRESS',
    'PERSON',
    'LOGIN',
    'MOBILEDEVICE',

    'BUSINESSUNIT',
    'DEPARTMENT',
    'EMPLOYEE',
    'PAYROLL',
    'LOAN',

    'PRODUCT',
    'PRODUCTBOM',
    'MATERIAL',
    'MATERIALPURCHASEORDER',
    'PRODUCTIONORDER',
    'SUPPLIER',
    'WORKCENTER',
    'MACHINE',
    'MACHINESPAREPART',
    'PROCESS',
    'PROCESSSTEP',
    'WORKCENTERJOB',

    'SALESREGION',
    'SALESREP',
    'SHIPPER',
    'CUSTOMERORDER',
    'CUSTOMERRETURN',
    'SALESREPFIELDREPORT',
    'SHIPMENT',
    'CONSIGNMENT',
    'VEHICLE',

    'NOTE',
    'TODOLIST',
    'STORE'
);

CREATE TYPE DATATYPE  AS ENUM (
    'STRING',
    'INTEGER',
    'DOUBLE',
    'DATE',
    'BOOLEAN',
    'SINGLELIST',
    'MULTILIST'
);


CREATE TYPE EMPLOYEE_STATUS AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'LEFT',
    'LAIDOFF'
);

CREATE TYPE CUSTOMERORDER_STATUS AS ENUM (
    'NEW',
    'APPROVED',
    'CANCELLED',
    'PROCESSING',
    'PROCESSED',
    'PARTIALLYSHIPPED',
    'SHIPPED',
    'DELIVERED'
);

CREATE TYPE ORDER_TYPE AS ENUM (
    'PRODUCT',
    'SAMPLE',
    'PROD',
    'MPO'
);

CREATE TYPE PRODUCT_STATUS AS ENUM (
    'ACTIVE',
    'OUTOFSTOCK',
    'DISCONTINUED'
);

CREATE TYPE SHIPMENT_STATUS AS ENUM (
    'PENDING',
    'SHIPPED',
    'CANCELLED'
);

CREATE TYPE ORDERVERIFICATION_STATUS AS ENUM (
    'PENDING',
    'VERIFIED'
);

CREATE TYPE CONSIGNMENT_STATUS AS ENUM (
    'PENDING',
    'SHIPPED',
    'FINISHED'
);

CREATE TYPE PRODUCTIONORDER_STATUS AS ENUM (
    'CREATED',
    'CANCELLED',
    'APPROVED',
    'REJECTED',
    'INPRODUCTION',
    'COMPLETED',
    'WAITINGFORMATERIAL'
);

CREATE TYPE MATERIALPURCHASEORDER_STATUS AS ENUM (
    'CREATED',
    'DELIVERED',
    'APPROVED',
    'CANCELLED'
);

CREATE TYPE INVENTORYRECORD_TYPE AS ENUM (
    'STOCKIN',
    'STOCKOUT'
);

CREATE TYPE LOAN_STATUS AS ENUM (
    'NEW',
    'APPROVED',
    'UNPAID',
    'PAID'
);

CREATE TYPE TIMEOFF_STATUS AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
  
);

CREATE TYPE RETURN_STATUS AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'

);

CREATE TYPE JOB_STATUS AS ENUM (
    'CREATED',
    'SCHEDULED',
    'STARTED',
    'FINISHED'
);

CREATE TYPE PAID_BY AS ENUM (
    'SELF',
    'CUSTOMER'
);

CREATE TYPE ATTENDANCE_STATUS AS ENUM (
    'P',
    'A'
);

CREATE TYPE DELIVERY_MODE AS ENUM (
    'WITH_PASS',
    'DOOR_DELIVERY',
    'ORDINARY'
);

CREATE TYPE BOM_TYPE AS ENUM (
    'TYPE',
    'CATEGORY',
    'PRODUCT'
);

CREATE TYPE BOMITEM_TYPE AS ENUM (
    'TYPE',
    'CATEGORY',
    'MATERIAL'
);
/* End enums */