/* Begin sequences */

CREATE SEQUENCE ROW_ID_SEQ                      START 1 INCREMENT 1;
CREATE SEQUENCE OBJECT_ID_SEQ                   START 1 INCREMENT 1;
CREATE SEQUENCE ATTRIBUTE_ID_SEQ                START 1 INCREMENT 1;
CREATE SEQUENCE LOV_ID_SEQ                      START 1 INCREMENT 1;
CREATE SEQUENCE AUTONUMBER_ID_SEQ               START 1 INCREMENT 1;


CREATE SEQUENCE COUNTRY_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE STATE_ID_SEQ                    START 1 INCREMENT 1;
CREATE SEQUENCE DISTRICT_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE ADDRESSTYPE_ID_SEQ              START 1 INCREMENT 1;
CREATE SEQUENCE ADDRESS_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE DEVICE_ID_SEQ                   START 1 INCREMENT 1;


CREATE SEQUENCE PRODUCTTYPE_ID_SEQ              START 1 INCREMENT 1;
CREATE SEQUENCE PRODUCTCATEGORY_ID_SEQ          START 1 INCREMENT 1;
CREATE SEQUENCE PRODUCT_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE PRODUCTBOM_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE MATERIALTYPE_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE MATERIALCATEGORY_ID_SEQ         START 1 INCREMENT 1;
CREATE SEQUENCE MATERIAL_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE PRODUCTIONORDER_ID_SEQ          START 1 INCREMENT 1;
CREATE SEQUENCE MATERIALPURCHASEORDER_ID_SEQ    START 1 INCREMENT 1;
CREATE SEQUENCE WORKSHIFT_ID_SEQ                START 1 INCREMENT 1;
CREATE SEQUENCE WORKCENTER_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE MACHINE_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE PROCESSL_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE PROCESSSTEP_ID_SEQ              START 1 INCREMENT 1;
CREATE SEQUENCE SPAREPARTL_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE WORKCENTERJOB_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE ITEM_ID_SEQ                     START 1 INCREMENT 1;



CREATE SEQUENCE PERSON_ID_SEQ                   START 1 INCREMENT 1;
CREATE SEQUENCE PERSONTYPE_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE EMPLOYEE_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE DEPARTMENT_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE EMPLOYEETYPE_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE PAYROLL_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE ALLOWANCETYPE_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE DEDUCTIONTYPE_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE LOANTYPE_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE LOAN_ID_SEQ                     START 1 INCREMENT 1;
CREATE SEQUENCE TIMEOFFTYPE_ID_SEQ              START 1 INCREMENT 1;


CREATE SEQUENCE LOGIN_ID_SEQ                    START 1 INCREMENT 1;
CREATE SEQUENCE SESSION_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE ROLE_ID_SEQ                     START 1 INCREMENT 1;
CREATE SEQUENCE PERMISSION_ID_SEQ               START 1 INCREMENT 1;


CREATE SEQUENCE SALESREP_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMERTYPE_ID_SEQ             START 1 INCREMENT 1;
CREATE SEQUENCE SALESREGION_ID_SEQ              START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMER_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE SHIPMENT_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE SHIPPER_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE CONTACTPERSON_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMERORDER_ID_SEQ            START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMERRETURN_ID_SEQ           START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMERRETURNREASON_ID_SEQ     START 1 INCREMENT 1;
CREATE SEQUENCE CUSTOMERODERREMINDER_ID_SEQ     START 1 INCREMENT 1;


CREATE SEQUENCE ATTACHMENT_ID_SEQ               START 1 INCREMENT 1;
CREATE SEQUENCE COMMENT_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE MESSAGE_ID_SEQ                  START 1 INCREMENT 1;
CREATE SEQUENCE REMINDER_ID_SEQ                 START 1 INCREMENT 1;
CREATE SEQUENCE NOTE_ID_SEQ                     START 1 INCREMENT 1;
CREATE SEQUENCE TODOITEM_ID_SEQ                 START 1 INCREMENT 1;

/* End sequences */
