<treasure-overlay-spinner active='spinner.active'>
<div class="row">
    <div class="styled-panel col-md-8 col-md-offset-2">
        <h3 style="text-align: center;">New Login</h3>
        <br/>
        <div>
            <button ng-if="loginCreated" class="btn btn-success" ng-click="createAnother()">Create Another</button>
        </div>
        <div class="grid-form">
            <div class="row"></div>

            <div class="row">
                <div class="col-sm-4 text-primary text-right" style="padding-top:10px;">Employee: </div>
                <div class="col-sm-8">
                    <ui-select ng-model="newLogin.person" theme="bootstrap" style="width:100%">
                        <ui-select-match allow-clear="true"  placeholder="Select an employee">{{$select.selected.firstName}}</ui-select-match>
                        <ui-select-choices repeat="employee in employees | filter: $select.search">
                            <div ng-bind-html="employee.firstName | highlight: $select.search"></div>
                        </ui-select-choices>
                    </ui-select>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 text-primary text-right" style="padding-top:10px;">Login Name: </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" ng-model="newLogin.loginName"/>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 text-primary text-right" style="padding-top:10px;">Password: </div>
                <div class="col-sm-8" style="padding-top: 8px;">
                    Password will be generated by the system
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 text-primary text-right" style="padding-top:10px;">Phone (to send SMS): </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" ng-model="newLogin.phone"/>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 text-primary text-right" style="padding-top:10px;">Email (and/or to send email): </div>
                <div class="col-sm-8">
                    <input type="email" class="form-control" ng-model="newLogin.email"/>
                </div>
            </div>
        </div>
        <br/>
        <div style="text-align: center">
            <button class="btn btn-default mr20" ng-click="cancelNewLogin()">Close</button>
            <button ng-disabled="loginCreated" class="btn btn-primary"  ng-click="createNewLogin()">Create</button>
        </div>
    </div>
</div>
</treasure-overlay-spinner>